pudl/constants.py
It looks like the EIA has changed their base URL from `https://www.eia.gov/electricity/data/eia923/archive/xls` to `https://www.eia.gov/electricity/data/eia923/xls` for all years before 2017.
Probably don't merge this yet. The URL is wrong for the not-yet-finalized 2017 data. How do you want to handle that?
=> Update URL for EIA form 923

pudl/datastore.py, scripts/update_datastore.py
I was having issues with unzipping (because of the URL issues in #140), so I thought I would download, then unzip.  This pull request makes that possible—you previously had to download the files new every time.
Is this helpful?  I'm happy to change the flag names around or make the docs more clear too.
=> Feature request: add a --no-download flag to update_datastore

docs/getting_started_pc.md, docs/requirements_conda.txt, pudl/load.py
Two changes here:
- Tell `open` to use UTF-8 when `load.py` is reading data into `postgres_copy`
- Avoids issues with "Tracy 4&5-Piñon Pine" when python defaults to an encoding that isn't UTF-8.
- Document the install process on Windows (copying substantially from the getting_started_mac instructions.
- I changed the recommendations a bit on installing Conda and Github Desktop, but that's just because I'm documenting my own install and I haven't played with Github Desktop.
=> Windows issues

docs/getting_started_for_linux.md, docs/getting_started_mac.md, docs/requirements_conda.txt, pudl/settings.py
Let me know what you think!
Changes:
- Rely on the user having a `.pgpass` file for the `catalyst` postgres user
- Changes in `settings.py`:
- Connect with IPv4 (127.0.0.1) instead of local unix socket
- Don't supply a password (will use .pgpass instead)
- Add and edit documentation for these changes
- Note that windows and linux don't require `catalyst` to be a postgres superuser. It would be nice if these changes meant os x didn't either, but I'm not at all certain.
I've tested these changes in linux, but not windows or os x. If these look okay, could you please test them on a mac before merging?  This will require creating a .pgpass file with a line like `127.0.0.1:*:*:catalyst:`
Sorry for all the configuration PRs. I promise I'll look at EIA 860 stuff once I actually have things …
=> Setup and postgres changes

docs/getting_started_for_linux.md, docs/getting_started_mac.md, docs/getting_started_pc.md, docs/requirements_conda.txt
- Add options for clone to mac instructions (`git clone` or Github
Desktop)
- Fix order of instructions: need to clone repo before installing Python
packages
- Fix missing `;` in Mac postgres commands
- Remove `.pgpass` from Mac postgres; the default config doesn't need it
=> Minor changes to installation docs

pudl/analysis.py, pudl/datastore.py, pudl/extract/eia860.py, pudl/extract/eia923.py, pudl/extract/ferc1.py, pudl/init.py, pudl/mcoe.py, pudl/outputs.py, pudl/transform/eia.py, pudl/transform/eia860.py, pudl/transform/eia923.py, pudl/transform/ferc1.py, pudl/transform/pudl.py, pudl/zipper.py, scripts/update_datastore.py, test/mcoe_test.py
Since python doesn't require parentheses for `if` or `return` statements, many [style guides](https://google.github.io/styleguide/pyguide.html?showone=Parentheses#Parentheses) recommend against them. I've removed them from this code and re-run the tests.
Feel free to reject this PR!  It's not a big deal to include the extra parentheses.
Also worth noting, I think the line `if(page == 'boiler_generator_assn', 'utilty'):` in extract/eia860.py was a typo.  I replaced it with `if 'report_year' not in newdata.columns:`, but let me know if that's incorrect.
https://github.com/catalyst-cooperative/pudl/compare/master...karldw:python-formatting-changes#diff-fdb815569da69b17883b51b869df04cbL177
=> Python formatting changes: remove parentheses

pudl/constants.py, pudl/extract/eia923.py, pudl/extract/epacems.py, pudl/init.py, pudl/load.py, pudl/models/epacems.py, pudl/transform/eia923.py, pudl/transform/epacems.py, scripts/init_pudl.py, setup.cfg, test/etl_test.py
- Add `fac_id` and `unit_id` variables to data where they're missing,
so the load into `BulkCopy` can always expect the same columns
- Add integer fixes for `fac_id` and `unit_id`
- Make `fac_id` column a `SmallInteger` (max value is 8421)
- Make `state` column an `Enum`
- Correct Enum values
- Format CEMS Enums in all caps for style
- Correct index names to use 'operating' instead of 'op'
- Improve help messages in `BulkCopy` (about which columns didn't
match) and `init_pudl.py` (about how to load all CEMS states)
=>  More improvements to CEMS

environment.yml
Commit https://github.com/catalyst-cooperative/pudl/commit/8395b4e90a7f40630812f357cf4daf94b3a248e7 added scikit-learn to the FERC1 transform. This PR adds it to the package list too.
=> Require scikit-learn

pudl/init.py, scripts/init_pudl.py
It's a pain, particularly with the CEMS data, to get partway through and realize the files you need aren't in the datastore. This `verify_input_files` function checks that they're all present before starting.
=> Check that all files exist before starting

README.md, pudl/constants.py, scripts/settings.yml
The 2018 hourly CEMS are now [available](ftp://newftp.epa.gov/DMDnLoad/emissions/hourly/monthly/2018/). This commit adds them in.
I also changed the `epacems_years` in `settings.yml` to mention the 1995-1999 data, which are less complete than later years, but can still be ingested.
=> Add 2018 CEMS

scripts/epacems_to_parquet.py
- The `extract` and `transform` functions no longer accept a `verbose` argument
- A few of what were category types are actually integers
- Parquet doesn't benefit from using specialized integer types (16-bit or unsigned)
- They're apparently all treated as int32, int64, or int96 internally
=> Clean output types and verbose arguments in epacems_to_parquet.py

src/pudl/analysis/mcoe.py
In investigating null fuel cost calcs, I narrowed in on the fuel cost 
output func being a source of the loss of fuel cost values. This 
function used to use the generation table from 923, probably as a 
vestige of having developed a lot of these output functions before we 
really integrated 860.
=> fuel cost output to ref 860 generators.

.pre-commit-config.yaml, devtools/environment.yml, devtools/jupyterlab_build.sh, setup.py, src/pudl/analysis/demand_mapping.py, src/pudl/extract/excel.py
Simplified and generalized the `categorize_eia_code()` function to allow either balancing authorities or utilities to take precedence, and to allow a specific set of utility and balancing authority IDs to be passed in. This will let us compile a set of individual utility IDs that we want to override the default balancing authority IDs if need be -- using all BA and all Util IDs and setting the priority to Utility just means everything (except 4 entities) are interpreted as utilities which is... clearly not right.
Closes #628
* Changed the loglevels for log output in the Excel extractor to use a variety of debug, info, warning, so that we can have more or less output as desired -- rather than having basically everything at info, per feedback from @ptvirgo 
* Updated `pudl-dev` environment …
=> Categorize eia codes with either Util or BA priority

src/pudl/convert/datapkg_to_sqlite.py
Merging datapackages is very fast, and this script is really just about loading
a bundle of datapackages into SQLite (hence the name) so I've simplified the
options to focus on doing just those things, and to only store the merged
data package temporarily, in an automatically generated temporary directory,
until the SQLite load is finished.
This change was inspired by accidentally wiping out an entire pudl-work
directory including all downloaded data by giving the script a bad argument
for the output directory path in conjunction with the --clobber arg!
Now --clobber only pertains to the sqlite database file.
Closes #711
=> Simplify datapkg_to_sqlite script

src/pudl/etl.py, src/pudl/helpers.py
Rather that checking for existence of individual datapackages and
clobbering them (if requested), apply the existence / clobbering to
whole datapackage bundles, since we don't want incompatible datapackages
accumulating within a supposedly unified bundle accidentally.
Closes #713
=> Clobber datapackage bundles not single datapackages

.github/workflows/build-docker-image.yml, devtools/print_requirements.py, release/Dockerfile.tiny
- Run the github action on every commit to master, dev, sprint branches.
- Set image entrypoint to simply kick off pudl_etl (this will be
appropriate when ferc1_to_sqlite and other parts of the pipeline
are integrated into this main script).
- Extract install requirements and pip install those prior to injecting
pudl source code, use experimental features that mount pip caches when
building containers. These efforts should improve our ability to build
images quicker and to reuse native docker layer caching because
requirements should only change infrequently whereas the source code
will change often.
=> Automate docker image builds

src/pudl/load/csv.py
The default behavior for gzip files is to add mtime timestamp to the header which results in non-deterministic checksum of the resulting files even if the content is the same.
Integration between pandas and gzip that allows writing compressed gzip files does not easily allow clearing the mtime attribute even though GzipFile library allows that (see https://github.com/pandas-dev/pandas/issues/28103 for more details).
This change works around this problem using the solution suggested in the pandas bug discussion. Unfortunately, it requires some dirty work to construct iobuffer wrapped zipfiles by hand and passing those to pandas instead of relying on it the native pandas/gzip integration.
Deterministic checksums are necessary if we want to have truly reproducible results and will make it …
=> Ensure deterministic checksums on csv.gz outputs

src/pudl/output/pudltabl.py
In working through the tutorial notebooks, I realized we never added these methods for the interim EIA 861 tables, so I went ahead and did it. Would still love to make these kinds of accessors much more automatic with some kind of factory method or something, if you have any suggestions on the right way to do that @rousik.
=> Add output methods for all remaining EIA 861 tables.

src/pudl/transform/ferc714.py
`pudl.transform.ferc714.demand_hourly_pa` took about 10 minutes to complete on 14 years of data. As of now, I have it down to 15 s.
Below are some of the steps I took to speed things up. Timings below are for a single year (2006).
- Since `report_date` format is consistent, use an explicit `format=` in `pd.to_datetime`. 
```python
pd.to_datetime(df.report_date)
pd.to_datetime(df.report_date, format="%m/%d/%Y %H:%M:%S", exact=True)
```
- Format all columns used as `id_vars` in `pd.DataFrame.melt` *before* they are replicated (25 times in this case) in the melt.
```python
df.pipe(_standardize_offset_codes, offset_fixes=OFFSET_CODE_FIXES)
```
- Similarly, drop any unused columns (i.e. the 25th hour) before the melt.
- Compute hour timedeltas once for each hour, rather than nyears * …
=> Speed up FERC 714 hourly demand transform

src/pudl/package_data/meta/datapkg/datapackage.json
hourly_emissions_epacems goodtables validation constraints did not recognize AK as a valid state.
I have been to Alaska and I can attest it does in fact exist.
=> Alaska is a thing

.github/dependabot.yml, devtools/environment.yml, docs/api/pudl.analysis.timeseries_cleaning.rst, setup.py
At @ezwelty's suggestion (after some unexpected breakage) I've tried to set minimum and maximum versions for all of our direct dependencies in `setup.py` so that unexpected major breaking updates should be much less frequent. I'm not entirely sure how this will interact with our use of `environment.yml` to specify the `pudl-dev` environment, but so far it seems to work fine with `tox` and `pip`. Recreating my `pudl-dev` environment locally from scratch, and then installing pudl inside it using pip seems to work fine though.
=> Specify min/max versions for all dependencies in setup.py

src/pudl/helpers.py, src/pudl/transform/eia860.py, src/pudl/transform/eia923.py
Fix `FutureWarning` complaining  about the change of default behavior w.r.t. to str.replace and regexes.
=> Regex future warning

src/pudl/output/ferc714.py
Implements the fixes enumerated in #618 by either modifying the utilities associated with a balancing authority for a given year ("Alter geometries") or by removing mention of a balancing authority, optionally reassigning its utilities to a balancing authority that lists it as a utility ("Treat as Utilities not Balancing Authorities").
=> Adjust FERC 714 service territories by using modified versions of EIA 861 tables

.pre-commit-config.yaml, devtools/environment.yml, tox.ini
I added the unit tests that @ezwelty created for the `timeseries_cleaning` module into the CI -- but they're under the `test` driectory, while the unit tests written by @rousik are under `src/pudl` -- we should come to a consensus on where these should live.
I also switched to using `tox -e unit` in the `pre-commit` instead of `pipenv run pytest src/pudl` both to ensure that any changes made to what constitutes "unit" tests in `tox` are reflected in the pre-commit settings, and also to avoid needing to add `pipenv` to the overall environment specification (it failed when I tried to run it because it wasn't part of my environment)
=> Timeseries unittest

src/pudl/workspace/datastore.py, src/pudl/workspace/resource_cache.py
Add capability to list available partition keys and known values.
=> pudl_datastore --list-partitions

.github/workflows/tox-pytest.yml, docs/api/pudl.convert.censusdp1tract_to_sqlite.rst, docs/api/pudl.convert.rst, docs/api/pudl.output.censusdp1tract.rst, docs/api/pudl.output.rst, setup.py, src/pudl/__init__.py, src/pudl/analysis/service_territory.py, src/pudl/convert/censusdp1tract_to_sqlite.py, src/pudl/convert/ferc1_to_sqlite.py, src/pudl/output/censusdp1tract.py, src/pudl/output/ferc714.py, src/pudl/workspace/datastore.py, src/pudl/workspace/setup.py
Rather than the ad-hoc ETL that we were using to extract the zip archive
of the Census DP1 GeoDataBase into a local folder, this commit treats the
DP1 as a standard data source, and converts it into an SQLite DB alongside
the PUDL and FERC 1 DBs in the PUDL_OUT/sqlite directory. It uses GDAL's
`ogr2ogr` command line utility to do this, calling it as a subprocess. This
means that this utility will need to be installed on your system for it to
work. Our `pudl-dev` conda environment will install it for you, or it can
be installed in /usr/bin/ogr2ogr with `apt install gdal-bin`. Other non-conda
installation options are certainly possible but... it'll get complicated to
cover all of them. Hopefully this setup will work fine in our Docker and CI
environments, and anyone else who is using it on …
=> Convert Census DP1 to SQLite

src/pudl/helpers.py, test/validate/eia860_test.py
small xfail ownership test which corresponds to #1116
and make pudl.helpers.count_records() faster by switching `agg({column: 'sum'})` to `[column].sum()`
=> add xfail test for ownership tbl and make count_records FASTER

src/pudl/analysis/allocate_net_gen.py, src/pudl/output/eia923.py, test/integration/fast_output_test.py
The cleanup of the clean_merge_as_of() function that Zane did (was great, no shade) was breaking the MCOE outputs when the allocate_net_gen flag is True. 
The generation table had different columns than the allocated generation table. The previous merges in the MCOE outputs were more "grab all of the columns every every single time" so it really didn't matter previously that these two tables had different columns and were being used interchangeably in the outputs. It was not ideal but not broken, and with the cleanup... it became broken.
**The solution**: Basically I pulled out all of the de-normalization of the generation table from the main generation output function (`pudl.output.eia923.generation_eia923`) into a stand-alone function so it can be used in both the main generation …
=> make generation allocation output mirror the standard generation table.

devtools/databeta.sh, devtools/environment.yml
There's a bug in JupyterLab 3.1.6-3.1.7 that causes notebook cells to
get skipped, hidden, or deleted when running all cells, or individual
cells. This was happening in the pudl-examples notebooks when I was
trying to compile the data release for v0.4.0. I pinned the environment
in that repo to 3.1.0-3.1.4, and have done so in the environment file
here as well.
Also checking in the databeta.sh script as it was used to generate the
data release which is currently uploading to Zenodo.
=> Dependency and data release script updates

src/pudl/metadata/resources.py, src/pudl/transform/eia860.py
Targeted drop of two rows in the `ownership_eia860` table during
transform. They had (literal) `nan` string values in the `generator_id`
column at that stage, which become true `pd.NA` values in the data type
assignment function later on, causing primary key constraints to be
violated.
Closes #1207
=> Drop rows with null generator_id in ownership_eia860

src/pudl/metadata/resources.py, src/pudl/transform/eia.py, src/pudl/transform/eia860.py
This fixes a couple of issues that flowed from owner IDs being reported in the operator ID column in the `ownership_eia860` table, as well as the accidental omission of the `plants_eia860` table from the list of exceptions in the harvesting process (where utility ID should be retained.
=> Fix utility_id_eia issues in ownership & plants tables

src/pudl/output/pudltabl.py
During the transform process, some of the EIA861 tables are broken down into multiple tables for normalization purposes. As a result, the table names are not the same as the raw tables. For example: 
`demand_side_management_eia861 ` becomes:
* `demand_side_management_sales_eia861`
* `demand_side_management_ee_dr_eia861 `
* `demand_side_management_mis_eia861 `
I fixed the output tables to reflect these outputs. Previously the code was returning a nonetype object when you ran `pudl_out.demand_side_management_eia861()`
=> Add missing output tables to EIA861

src/pudl/metadata/resources.py
We split the nuclear units out from `generation_fuel_eia923` in #1296 because nuclear fuels are reported at the generation unit level and non-nuclear unit fuels are reported at the plant, prime mover, and fuel level. [Some users](https://twitter.com/CatalystCoop/status/1456346092270862336) were confused by this so I included this explanation in the `generation_fuel_eia923` data dictionary docs.
=> Update generation_fuel_eia923 documentation with nuclear unit change.

devtools/datasette/metadata.yml, src/pudl/output/eia923.py, test/integration/fast_output_test.py, test/validate/eia_test.py, test/validate/ferc1_test.py, test/validate/mcoe_test.py
There are several changes here beyond the number of rows that we expect to see in each table which I would like to get some other eyeballs on quickly, including addition of new output tables and the way that we are looking for primary keys that uniquely identify records in the aggregated output tables.
=> Validate v0.5.0

setup.py
Jinja2 versions 2.x or 3.x appear to work with our system, and the restriction to only 3.x was causing some version conflicts downstream in the OS-C environment, so I expanded the range of allowable versions. See #1352
=> Widen allowable Jinja versions to 2-3

.github/workflows/tox-pytest.yml, devtools/ci-environment.yml, devtools/environment.yml, setup.py
With the exception of `numba` all of our dependencies now appear to be working with Python 3.10, and the tests are passing, so it seems like PUDL works with Python 3.10 now.  I think the biggest advantage for us at this point is the improvements that have been made to error messages, to make them more specific.
`numba` v0.55 (the next major release) is expected to [support Python 3.10](https://github.com/numba/numba/issues/7562). This isn't a strict requirement for our code -- it just speeds some things up. It'll probably come out in a few weeks. For now I've commented `numba` out of the `devtools/environment.yml` file.
I've also disabled `fast-fail` in the GitHub Actions testing matrix so that if the tests fail for one version of Python, it'll still try and run them for all the rest. …
=> Add support for Python 3.10

src/pudl/analysis/allocate_net_gen.py
bb pr. this fixes two instances of dtype loss in the portion of the allocate_net_gen process that only gets run on the generators that do not have prime movers. This process is currently only run on the RMI hub teams older years of EIA. In PUDL old EIA years, we have been effectively back-filling through the harvesting process.
The whole process for generators w/o prime movers will be retired as soon as the RMI team converts over to using PUDL's pre-processed data as their main EIA input - which is on the docket!
=> Allocate dtype fix

devtools/environment.yml, pyproject.toml
=> Constrain setuptools to <60.0.0 in environment.yml and pyproject.toml to avoid breaking changes

src/pudl/constants.py, src/pudl/metadata/codes.py, src/pudl/metadata/fields.py, src/pudl/metadata/labels.py, src/pudl/metadata/resources/__init__.py, src/pudl/metadata/resources/eia.py, src/pudl/metadata/resources/eia860.py, src/pudl/metadata/resources/eia861.py, src/pudl/metadata/resources/eia923.py, src/pudl/metadata/resources/epacems.py, src/pudl/metadata/resources/ferc1.py, src/pudl/metadata/resources/ferc714.py, src/pudl/transform/eia860.py, src/pudl/transform/eia861.py, tox.ini
Getting the table-level metadata integrated into `dev` now will help @katie-lamb close #1253 
To that end this PR does:
=> Separate resource definitions by data source

devtools/environment.yml, pyproject.toml
Update a couple of build environment packages that don't get automatically bumped by dependabot since they aren't in `setup.py`. Also replace the huge and old `jupyter_contrib_nbextensions` package with the small and current `nbconvert` which is all we really need to clear notebook outputs in pre-commit land.
=> Update to pip 22, setuptools 61. Add nbconvert to pudl-dev

.gitignore, devtools/environment.yml
The `dask-labextension`, `py-spy`, `nbdime` and `seaborn` packages are only used occasionally and only by some people, so I wanted to pull them out of the default `pudl-dev` environment to slim it down a little bit.
=> Remove some seldom used dependencies from pudl-dev environment.yml

.github/workflows/tox-pytest.yml, docs/release_notes.rst, setup.py, src/pudl/output/epacems.py, src/pudl/package_data/settings/etl_fast.yml, src/pudl/package_data/settings/etl_full.yml, test/integration/epacems_test.py, test/test-environment.yml
Dask introduced breaking changes to `dd.read_parquet()` in v 2022.4.2:
https://docs.dask.org/en/stable/changelog.html#v2022-04-2
However, we didn't catch this when it happened because it's only a
problem when there's more than one row-group. So now I'm processing
2019-2020 data for both ID and ME (two of the smallest states).  I was
already processing 4 state-years when testing the parallelized CEMS ETL
so this isn't any more data that we were pulling before.
Also fixed a bug that the parallelized ETL test introduced, where it was
writing the partitioned output to the same directory as the other CEMS
output, which might have been creating weird behavior.
I put more stringent bounds around the Dask versions in `setup.py` so
we'll at least be notified by @dependabot if a version changes …
=> Fix breakage resulting from dask v2022.4.2

src/pudl/transform/eia861.py
Proposing a minor change to how balancing authority fixes are applied so that not all years of data are required to make the fixes work. This should address #828.
In the existing process, when I try do something like this:
```python
pudl_out = PudlTabl(...)
pudl_out.etl_eia861(eia861_settings=Eia861Settings(years=sorted(range(2005, 2021)))
```
I get an error in these lines of code because there are values in `BA_ID_NAME_FIXES.index` that are not in `df.index`.
https://github.com/catalyst-cooperative/pudl/blob/6e71bfa1a848f67ffeb1f10a161af01db75073b8/src/pudl/transform/eia861.py#L859-L861
I played around a little bit and I think replacing that with the merge I suggest here addresses the problem and all the tests appear to pass when I run them locally.
Given the small size of the change, I …
=> Address issue where 861 ETL fails w/o all years of data

docs/release_notes.rst
As part of the list in [this release PR](https://github.com/catalyst-cooperative/pudl/issues/1683)...
I added release notes for the `date_merge` PR which also changed the plant parts list and MCOE tables to use a list of default columns from the EIA 860 generators table.
=> Release notes for date_merge and default columns change for PPL and MCOE

.bandit.yml, .codecov.yml, .github/FUNDING.yml, .github/dependabot.yml, .github/workflows/build-docker-image.yml, .github/workflows/pre-commit-ci-auto-merge.yaml, .github/workflows/tox-pytest.yml, .pre-commit-config.yaml, .readthedocs.yaml, devtools/environment.yml, docker-compose.yml, docs/docs-environment.yml, notebooks/work-in-progress/pudl-intake-catalog.yaml, release/settings/release.yml, release/settings/test.yml, src/pudl/package_data/settings/etl_fast.yml, src/pudl/package_data/settings/etl_full.yml, src/pudl/package_data/settings/ferc1_solo_test.yml, test/test-environment.yml
Folks have different YAML formatters in our code editors so we need a pre-commit hook to do the formatting for us!
=> Apply Yaml pre-commit formatter

devtools/environment.yml
Require Python 3.10 in our `pudl-dev` conda environment.  This was overlooked in the previous Lib to App PR.
=> Require Python 3.10 in the pudl-dev conda environment

.github/workflows/build-deploy-pudl.yml
Add build-deploy-pudl.yml to `main` because the workflow needs to be kicked off by the default branch.
=> Add build-deploy-pudl.yml to main

.github/workflows/build-deploy-pudl.yml
I forgot to pass the updated git ref to the GCE VM which resulted in incorrectly named buckets. This PR fixes that issue and renames the variable in the GitHub action.
I'm going to rerun the action before I merge it in.
=> Fix Github Ref bug

.github/workflows/build-deploy-pudl.yml, docker/Dockerfile
Unpin apt-get packages so we don't have to update the Dockerfile every time there is a new version of `curl` and `jq`. The most recent nightly build failed because it couldn't find an old version of curl. 
This PR also adds a step that notifies slack of the final status of the github action.
=> Unpin apt-get packages

.github/workflows/bot-auto-merge.yml, .github/workflows/pre-commit-ci-auto-merge.yaml, .github/workflows/tox-pytest.yml
Apply the same post-workflow `merge-me-action` to the dependabot PRs as we use for the pre-commit-ci merges, since the dependabot permissions within the `tox-pytest` workflow seem to be insufficient.
=> Fix dependabot automerge

src/pudl/analysis/mcoe.py, src/pudl/output/pudltabl.py
This fixes a bug with the default generator columns argument in the output tables for `mcoe`, `gens_mega`, and `plant_parts_eia` described in [this issue](https://github.com/catalyst-cooperative/pudl/issues/1755). The default generator columns argument was introduced through `date_merge`.
**What is the bug?**
The `plant_parts_eia` table relies on the `gens_mega` table and in turn the `gens_mega` table relies on the `mcoe` table. 
Each of these tables requires certain generator columns in order to be created. The `plant_parts_eia` table requires the most columns and the `mcoe` table requires the fewest number of columns. I initially thought it would be okay for each of these tables to have their own set of default generator columns (only the columns necessary for the creation of that …
=> Fix bug in gens mega and plant part list creation

.github/workflows/build-deploy-pudl.yml, .github/workflows/tox-pytest.yml, docs/dev/nightly_data_builds.rst, src/pudl/workspace/datastore.py, tox.ini
Tell Tox to tell pytest to default to pulling data from the GCS Cache in the Github CI workflow, to increase the reliability of the tests on here.
=> Use gcs cache in ci

src/pudl/workspace/resource_cache.py, test/unit/workspace/resource_cache_test.py
This PR retries GCS Cache requests on BadRequest errors to eliminate the flakiness in our nightly builds.
=> Patch nightly build flakiness

src/pudl/package_data/settings/etl_fast.yml, src/pudl/package_data/settings/ferc1_solo_test.yml, src/pudl/transform/ferc1.py
As of 8/31:
- Makes settings files line up with new settings classes/add both 2020 + 2021 so both xbrl and dbf are tested.
-  (If we merge in the `xbrl_steam_but_really` branch) PKs! which should break until we get #1705 under control
=> Update ETL settings files to work with XBRL+DBF and new Ferc1Settings

.github/workflows/build-deploy-pudl.yml, docker/gcp_pudl_etl.sh
I created a private copy of `zenodo-cache.catalyst.coop` called `zenodo-cache-internal` using the [gsutil rsync](https://cloud.google.com/storage/docs/gsutil/commands/rsync#using--d-option-with-caution-to-mirror-source-and-destination.) command. 
I also added a `gsutil rsync` step to the `build-deploy-pudl.yml` workflow to make sure the VM has the most recent data from `gs://zenodo-cache.catalyst.coop`. We could also flip this, so the public bucket follows the internal bucket. This might make more sense, given the nightly builds will update the internal bucket more frequently. What do your think @zaneselvans 
Hopefully this solves the random `BadRequest` errors 🤞
=> Use internal zenodo-cache bucket for nightly builds

src/pudl/transform/eia.py
Fill in a handful of BA codes w/ BA names.
There are two strange things in the PR (imo):
* how to grab the "correct" map between codes and names. There are three options:
* (my choice) use the cleaned/harvested/encoded plants table to compile the most frequently reported association of codes and names.
* build a lil map of names and codes that are known to have missing codes/known names. There aren't that many, but these names could stray so I don't love this:
``` 
bac_map = {
"Hawaiian Electric Co Inc": "HECO",
"PJM Interconnection, LLC": "PJM",
"Midcontinent Independent Transmission System Operator, Inc..": "MISO",
"Duke Energy Progress East": "CPLE",
}
```
* use the map in `CODE_METADATA`. I used the BA names as the `description` column, so we could use this. BUT this is an implied …
=> Fill in some null BA codes using BA names

devtools/eia-etl-debug.ipynb, src/pudl/transform/eia923.py
Fix the aggregation of the `data_maturity` column in the transform step for the `generation_fuel_nuclear_eia923` table, so the aggregated records we create (to fix some missing primary key values) get the `data_maturity` value of their input records and we don't have NA values messing things up downstream.
Also update the EIA ETL Debugging notebook to reflect the current state of the system on `dev`.
Closes #1914
=> Aggregate data_maturity in gfn_eia923, update EIA ETL debugging Notebook

src/pudl/output/eia860.py, src/pudl/transform/eia.py, src/pudl/transform/eia861.py
See #1909 for discussion. 
```
Filled BA codes where no treatment had been applied. Currently 43.9% of records (81266) with no BA codes
Filled BA codes where backfilling and consistent value is the same. Currently 11.1% of records (20574) with no BA codes
Filled BA codes where consistent code is PACW and state is OR or CA. Currently 10.9% of records (20110) with no BA codes
Filled BA codes where consistent code is PACE and state is UT. Currently 10.9% of records (20107) with no BA codes
Filled BA codes where SWPP is most consistent value. Filled w/ oldest BA code. Currently 8.3% of records (15445) with no BA codes
Filled BA codes where most consistent BA code is less than 80% consistent. Used backfilled BA code. Currently 8.3% of records (15396) with no BA codes
```
=> Fill in pre-2013 BA codes

src/pudl/metadata/sources.py
Updating the metadata for the EPA CAMD to EIA crosswalk, so that we can use it to create a new Zenodo archive of this data with the new name.
Hopefully this is the only file that needs to be updated. But if not we can grab additional ones piecemeal from the crosswalk branch as needed.
=> Update the name of the EPA CAMD to EIA crosswalk data source.

setup.py
Since updating to pandas-1.5, our nightly builds have doubled in memory use. I'm opening this PR to test the memory use with pandas 1.4.x.
=> Rollback pandas-1.5

src/pudl/analysis/state_demand.py, src/pudl/etl.py, src/pudl/metadata/classes.py, src/pudl/metadata/dfs.py, src/pudl/metadata/enums.py, src/pudl/metadata/fields.py, src/pudl/metadata/resources/eia860.py, src/pudl/metadata/resources/pudl.py, src/pudl/metadata/sources.py, src/pudl/transform/eia.py, src/pudl/transform/eia860.py
Consolidates several dictionaries and enumerations that we had scattered across the codebase into a single static table, with information about states, territories, provinces, etc. Including membership in various geographic aggregations, FIPS codes, etc.
In the process, also added a new `ownership_country` column to the `ownership_eia860` table, to clearly differentiate between country and political subdivision information, which was comingled in the state column previously.
Closes #1958
=> Add a static table of political subdivision attributes.

docs/release_notes.rst
I forgot to add release notes when I made the `political_subdivisions` table.
=> Add release notes about the new political_subdivisions table.

docs/dev/annual_updates.rst, docs/dev/pudl_id_mapping.rst, src/pudl/glue/ferc1_eia.py, test/integration/glue_test.py
Added some functions that add helpful-for-humans things like utility names and a flag for if an EIA plant is large enough to bother go linking it to FERC plants. Deployed those labeling functions in the `glue_test` module. I also standardized some of the naming of functions.
Also changes the docs pages about integrating a new year of data and about the ID mapping.
Closes #1981
=> Add labeling functions for manual maps

docs/release_notes.rst
Forgot to make release notes when we merged in #1998
=> Add release notes about EIA API removal / fuel price filling

test/validate/mcoe_test.py
I really don't know where I got those large values that were previously in there. But I glad it tripped a wire! Here's the updated version
=> Fix erroneous max row values in mcoe_test

src/pudl/transform/ferc1.py
Mostly just fixes all the bad references in the small gens transformer doc strings.
One other change is taking the `label_note_rows_group()` function out from inside the `label_note_rows()` function so that it would show up in the docs.
=> Fix doc stings for small gens table transform

setup.py, src/pudl/transform/ferc1.py, test/validate/ferc1_test.py
For the moment this points at the `dev` branch of the `ferc-xbrl-extractor` repo, which fixes an issue with the XBRL to SQLite conversion that was affecting the `fuel_ferc1` table in particular.
* Updates the expected row counts for the `fuel_ferc1` and `fbp_ferc1` data validations.
* Adds some additional logging to the `Ferc1AbstractTableTransformer.merge_instant_and_duration_tables_xbrl()` method.
* Defensively uses a copy of the `fuel_ferc1` table in the transformation of the `plants_steam_ferc1` table just to be sure that the table isn't accidentally mutated in the process of the steam transform.
=> Address missing fuel ferc1 records

.github/workflows/build-deploy-pudl.yml, docker/gcp_pudl_etl.sh
The most recent nightly build failed to shut down the VM because the region was hardcoded in the API request that shuts down the VM at the end of the nightly builds. This PR passes the GCE_INSTANCE_ZONE env var to the container on the VM.
following:
for details on how to run the full test suite locally if you need to debug a
particular failure.
descriptive enough for developers and users to understand your code.
[data validation …
=> Add GCP region/zone env var to nightly build scripts

src/pudl/metadata/resources/ferc1.py, test/validate/ferc1_test.py
we have one validation ferc1 test to check whether the record_id is unique, which doesn't apply to any of the column-> row reshaped tables. so we have to tell it to ignore those. + i added the shell of a table into the resources before it was ready so i disabled that one. we should use the transform params to find the tables to do this check on without having to enumerate each of these non-unique record_id tables
following:
for details on how to run the full …
=> fix ferc1 record_id validation errors

test/validate/ferc1_test.py
bb fix for the `electric_energy_sources_ferc1` table name change. it needed to be removed from the record_id valition test.
=> fix table name in record_id test

src/pudl/analysis/spatial.py
Shapely 2.0.0 [includes some breaking changes](https://shapely.readthedocs.io/en/stable/migration.html), including no longer treating `GeometryCollection` and `MultiPolygon` objects as iterable, which we were doing in a few places.  This PR simply updates our code to use the new iterable `.geoms` attribute of those classes.
=> Update our code to work with Shapely 2.0.0

src/pudl/analysis/epacamd_eia.py
In epacamd_eia.py when prepping the data for networkx, we created a new generator_id column that didn't have any overlapping id numbers. The problem was that this new unique id was assigned the same name as an existing column (generator_id), and this column was used as the target column in the network analysis. This was resulting in the final epacamd_eia crosswalk table missing a generator_id column. For our use in OGE, we need this crosswalk table to include the crosswalk to EIA generator ids.
To fix this, I just assigned the target column for the graph analysis a unique name that is different from the generator_id column.
=> fix missing generator_id

test/validate/ferc1_test.py
The number of expected plant records changed slightly, as we are now excluding a few more invalid plant names (like "not applicable" or the string zero "0".
=> Update row counts for dropped invalid plant names

src/pudl/transform/classes.py, src/pudl/transform/ferc1.py
Teeny tiny bb PR that adds the following code to the `TransformParams` class:
```
class Config:
"""Only allow the known table transform params."""
extra = "forbid"
```
And fixes a parameter name that was flip-flopped: 
- `xbrl_instant` and `xbrl_duration` were used as parameters in the `Ferc1TableTransformParams` class when the actual parameters defined in `RenameColumnsFerc1` are `instant_xbrl` and `duration_xbrl`. This PR flips them to reflect the `RenameColumnsFerc1` definition.
=> Make transform params stricter 2

.github/pull_request_template.md
* Comment out explanatory text so it doesn't gum up the PR.
* Shorten bullets and format so they don't look janktastic.
=> Update & simplify PR template formatting / language.

README.rst
We have publicly available nightly build outputs in some S3 buckets! We should let our users download it if they want. This PR just adds some links to the README. We may want to add similar links to other places too, see #2196. But this at least gets them out publicly somewhere we can refer to!
- ~[ ] Make sure you've included good docstrings.~
- ~[ ] For major data coverage & analysis changes, [run data validation tests](https://catalystcoop-pudl.readthedocs.io/en/latest/dev/testing.html#data-validation)~
- ~[ ] Include unit tests for new functions and classes.~
- ~[ ] Defensive data quality/sanity checks in analyses & data processing functions.~
- ~[ ] Update the [release notes](https://catalystcoop-pudl.readthedocs.io/en/latest/release_notes.html) and reference reference the PR and …
=> Add direct S3 nightly build download links to README.

src/pudl/transform/ferc1.py
When I was building a show-and-tell notebook for the Mines class I presented to, I noticed that there was a typo in the `FuelFix`s in the `standardize_physical_fuel_units`. Specifically, the fuel fix for nuclear was `FuelFix("nuclear", "mmmbtu", "mwhth", (1.0 / 3.412142)),` when it should have been `mmbtu` I removed the extra `m` here!
=> Change FuelFix for nuclear from mmmbtu to mmbtu

src/pudl/extract/xbrl.py, src/pudl/settings.py, test/conftest.py, test/integration/datasette_metadata_test.py, test/unit/extract/xbrl_test.py
This PR speeds up/improves XBRL extraction testing. To do so, it uses a subset of the XBRL filings during integration testing. This dramatically reduces the time required to extract XBRL filings, and seems to reduce total runtime for the CI by ~10 minutes. This PR also adds several unit tests focused on the extraction and XBRL `datastore` object.
=> Xbrl test speedups

.github/dependabot.yml, devtools/environment.yml, docs/docs-environment.yml, setup.py, test/test-environment.yml
* Pin SQLAlchemy<2.0 as [pandas doesn't yet support it](https://github.com/pandas-dev/pandas/issues/40686)
* Also update conda environments to allow pip 23.
* See #2267
=> Pin SQLAlchemy<2.0 and allow pip 23

.github/workflows/tox-pytest.yml, .gitignore, docs/dev/index.rst, docs/dev/infrastructure_as_code.rst, src/pudl/workspace/datastore.py, terraform/.terraform.lock.hcl, terraform/main.tf
Our GH actions GCloud authentication is broken for workflows that originate in forks - this is because repo-level secrets don't get passed into those runners by default. I guess that makes sense, and we probably shouldn't let people access our secrets just by pushing some malicious actions.
However! We can set up Workload Identity Federation, I think, which should avoid that problem - so here's a crack at that.
CI now passes for external PRs too: https://github.com/catalyst-cooperative/pudl/pull/2261
Separately, I took the opportunity to set these bits of infrastructure up through Terraform.
TODO:
=> Use Workload Identity Federation in GH Actions

src/pudl/cli.py, src/pudl/etl/__init__.py, src/pudl/extract/ferc1.py, src/pudl/extract/xbrl.py, src/pudl/ferc_to_sqlite/__init__.py, src/pudl/ferc_to_sqlite/cli.py, src/pudl/package_data/settings/etl_fast.yml, src/pudl/settings.py, test/unit/settings_test.py
This PR removes tables from the settings models/yaml files, as discussed in #2272.
As @bendnorman mentioned in the PR linked above, it looks like we could use dagster's [multi-asset subsetting](https://docs.dagster.io/concepts/assets/multi-assets#subsetting-multi-assets) to allow us to select subsets of tables, but I'm not sure if it's worth the time/energy. Open to other's thoughts on this though. Perhaps it's something we could leave to the future if we have time.
=> Remove tables from settings

.github/workflows/build-deploy-pudl.yml, .github/workflows/zenodo-cache-sync.yml, terraform/main.tf
This adds a bunch of new service account associations to the WIF provider we set up earlier, so that other repos can also use WIF instead of credentials.
I've already run `terraform apply` here so the changes should be reflected within GCP already.
Note that the `build-deploy-pudl` and `zenodo-cache-sync` actions are triggered via `schedule` and `workload_dispatch`, so the versions on `main` are the ones that will run. Which means that they'll continue to use the old credentials jsons until this lands in `main`.
=> Add more service accounts to Workload Identity Federation

.github/workflows/tox-pytest.yml, tox.ini
As we saw in #2224, [our datastores were still failing to connect to Google](https://github.com/catalyst-cooperative/pudl/actions/runs/4185969563/jobs/7253799219) because of
```
Unable to obtain credentials for GCS Cache at gs://zenodo-cache.catalyst.coop. Falling back to Zenodo if necessary. Error was: Project was not passed and could not be determined from the environment.
```
It turns out that we had not run the proper Google-related environment variables into the tox environments - this fixes that and also removes the credential file itself - why go to all the effort of WIF if you're just gonna dump the creds back to disk anyways, eh?
=> Fix google auth error in tox-pytest

devtools/materialize_asset.py
This is a small devtool to help us add breakpoints to code that runs in Dagster. Maybe there's a way to do this natively in the dagster CLI, but it was faster to write this code than search through the docs more.
Relates to #2318 and #2294 .
=> Breakpoints in Dagster

src/pudl/transform/eia.py
This small PR patches a fix to the recently merged #2312 , which fails when there are no `balancing_authority_codes_eia` or `balancing_authority_names_eia` in the dataset (e.g. when a user selects a subset of data prior to 2013). I've added a few lines here to skip the fixes if these conditions are met. 
To test the functioning of this fix:
- test the ETL on a pre-2013 data subset, ensuring it does not break.
- test the ETL on 2013 data (the year in which the fix occurs), checking to see that the number of 'PACW' and 'PACE' `balancing_authority_codes` changes between the raw extracted data and the end of the ETL, and that names that are changed match the corresponding BA code for these records.
E.g.:
```
eia860_raw_dfs['plant']['balancing_authority_name_eia'].value_counts()[['PacifiCorp - …
```
=> Fix balancing_authority_name update in cases where no ba_name_to_code_map()

test/unit/extract/xbrl_test.py
This PR fixes XBRL unit tests after the `dev -> dagster` merge. It uses `xbrl2sqlite` as an op instead of a normal function.
=> Fix xbrl extraction unit tests

src/pudl/extract/ferc1.py, test/conftest.py
Fix `xbrl_metadata_json` for tables where many XBRL tables map to a single clean table. Taken directly from `extract_xbrl_metadata` on `dev`.
=> Fix xbrl metadata extraction for many->one table map

src/pudl/workspace/datastore.py
Fixes #2315 (hopefully!)
While waiting for my CI to re-download everything because the cache is empty, I decided to jump in on this thing.
I cleared my data directory locally, ran integration tests with `--gcs-cache-path`, and watched as the local cache got populated, when it hadn't without this fix 😌
=> Update local cache when using `--gcs-cache-path`

devtools/materialize_asset.py, src/pudl/etl/static_assets.py, src/pudl/extract/eia860.py, src/pudl/extract/eia923.py, src/pudl/extract/ferc1.py, src/pudl/io_managers.py, src/pudl/output/ferc1.py, src/pudl/settings.py, src/pudl/transform/ferc1.py, test/conftest.py, test/unit/extract/xbrl_test.py
This PR resolves issues introduced in the dev -> dagster merge.
There are a couple of open issues:
**There are some changes in the database schema so I recommend deleting the pudl.sqlite files before debugging the ETL.** Bonus points if we can figure out how to compare the schema in the db and the schmea stored in the `pudl.metadata`.
=> Resolve dev -> dagster merge fixes

src/pudl/cli.py, src/pudl/ferc_to_sqlite/cli.py, src/pudl/helpers.py, src/pudl/workspace/setup.py, test/conftest.py
This PR addresses #2301 by setting `PUDL_OUTPUT` and `PUDL_CACHE` from `pudl_settings` if these env vars are not already set.
=> Configure dagster env vars from settings if not set already

README.rst
My browser gives me privacy errors when I try to download our s3 data from the link the readme because they use HTTP. I updated the URLs to use the https versions.
=> Update s3 bucket urls to use https

src/pudl/cli.py, src/pudl/etl/__init__.py, src/pudl/helpers.py, src/pudl/workspace/setup.py, test/unit/helpers_test.py
I realized we often run the ETL without EPA CEMS so it doesn't take forever. I created two pre-configured jobs that select all assets excluding the `hourly_emissions_epacems` and downstream assets. 
I also made some changes in the `pudl_etl` cli command so users can specify a settings file without epacems. This feels a little janky because the epacems settings are still floating around in the dataset_settings resource even though the assets that depend on epacems settings aren't being used. At some point, it might make sense to remove the dataset_settings resource and just configure the extraction assets directly.
=> Add jobs for excluding EPA CEMS assets

src/pudl/cli.py, src/pudl/convert/epacems_to_parquet.py, src/pudl/extract/ferc1.py, src/pudl/extract/xbrl.py, src/pudl/ferc_to_sqlite/cli.py, test/conftest.py
I noticed the `--loglevel` flag wasn't working for the CLI commands that execute dagster jobs. I couldn't find anything in the documentation about set log levels when running jobs using `execute_job`. I played around with where to set the log level and for some reason, settings the log level in the job functions works. [`dagster.reconstructable()`](https://docs.dagster.io/_apidocs/execution#dagster.reconstructable) didn't let me parameterize the job function so I had to use this confusing function called [`dagster.build_reconstructable_job()`](https://docs.dagster.io/_apidocs/jobs#dagster.build_reconstructable_job). This is working but when there are failures **it occasionally will not show the full stack trace...** it just says an asset or op failed. I'm chatting with someone on the …
=> Parameterize reconstructable jobs to set loglevel

docker/gcp_pudl_etl.sh
I forgot to do this before merging the nightly build stuff. But this is the easiest way for us to "make PRs into `main` from `dev` when nightly builds pass." Anything more than this requires pushing GH access into the ETL VM, etc.
=> Make nightly build message a little cleaner.

docs/release_notes.rst, src/pudl/extract/eia860.py, src/pudl/extract/eia860m.py, src/pudl/extract/eia861.py, src/pudl/extract/eia923.py, src/pudl/glue/epacamd_eia.py, src/pudl/settings.py, test/validate/eia_test.py, test/validate/mcoe_test.py, tox.ini
See #2366 for a description of the problem.
This (Draft) PR simply applies the same solution to `boiler_id` that we were already applying to `generator_id` in the extract phase of the EIA 860, 860m, 861, and 923 data.
- ~Make sure you've included good docstrings.~
- ~Include unit tests for new functions and classes.~
- ~Defensive data quality/sanity checks in analyses & data processing functions.~
Closes #2366
=> Fix inconsistently reported leading zeros in EIA boiler id

src/pudl/metadata/resources/eia860.py
By default the data is ordered by primary key in the DB, and the current ordering means that all boilers with the same boiler ID are grouped together, rather than all boilers within a given plant being grouped together, as is the case with generator ID.  I think it's more likely that folks would like to see all the boilers that are part of a given plant, than all plants that happen to have a boiler with ID "A1". Check out [`boilers_eia860` on our Datasette](https://data.catalyst.coop/pudl/boilers_eia860) to see what it looks like now.
=> Reorder PK of boilers_eia860 to group data like other tables

src/pudl/extract/ferc1.py, src/pudl/helpers.py
For some reason, `bandit` on CI is calling us out for more SQL injection vulnerabilities than it is locally.
First, try to fix the things they caught. Second, we should try to figure out why the `bandit`s differ.
=> Fix Bandit issues

docs/dev/nightly_data_builds.rst
Very small docs change that puts the `--no-sign-request` flag at the end of the command in the `nightly_data_builds.rst` docs page. The command wasn't working with the flag at the beginning.
Went from:
```
aws s3 cp --no-sign-request s3://intake.catalyst.coop/dev/pudl.sqlite ./ 
aws s3 cp --no-sign-request --recursive s3://intake.catalyst.coop/dev/ ./
```
to:
```
aws s3 cp s3://intake.catalyst.coop/dev/pudl.sqlite ./ --no-sign-request
aws s3 cp --recursive s3://intake.catalyst.coop/dev/ ./ --no-sign-request
```
=> Move `--no-sign-request` to the end of the command in the nightly_data_build docs

.pre-commit-config.yaml, setup.py, src/pudl/helpers.py, src/pudl/io_managers.py
* I ran the full ETL locally with the new version of Dagster (it's so fast!) and it passed fine. I think it also makes the asset graph more readable.
* Also pulled in the `bandit` fixes.
=> Bump allowed range of Dagster versions to >=1.1,<1.3

src/pudl/cli.py, src/pudl/helpers.py, src/pudl/io_managers.py, src/pudl/metadata/classes.py
This PR handles filtering tables out of the `pudl.sqlite` schema that should not be included, as discussed in #2294. It does this by adding the ability to exclude `etl_groups` when constructing a `Package`.
=> Dagster filter table schemas

.github/workflows/tox-pytest.yml, devtools/datasette/publish.sh, docker/gcp_pudl_etl.sh, docker/local_pudl_etl.sh, src/pudl/cli.py, src/pudl/ferc_to_sqlite/cli.py, src/pudl/io_managers.py, src/pudl/resources.py, src/pudl/workspace/setup.py, src/pudl/workspace/setup_cli.py, test/conftest.py, tox.ini
Closes #2396 .
We should rename the confusing stuff *before* we merge into `dev`.
=> Rename PUDL_CACHE to PUDL_INPUT

docs/dev/run_the_etl.rst, setup.py, src/pudl/etl/check_foreign_keys.py
Renamed `check_pudl_fks` to `pudl_check_fks` to follow the naming we've tried to have on our other CLI scripts (as suggested by @karldw waaaay back in #460).  We still don't do this on the commands with long names, but it's easy to do here.
=> Rename check_pudl_fks to pudl_check_fks to align w/ other CLI names

setup.py
Pin `grpcio==1.46.1` in **both** conda `environment.yml` and `setup.py` so that we definitely get this one version, and it's hopefully provided by conda, since there are some issues with the pip installed arm64 (Apple silicon). I've been having cases where pip seemingly overrules the conda version and updates to 1.47.5 which then doesn't work, breaking dagster.
This problem should go away when we move to Python 3.11 since the we can use the newest versions of `grpcio` I think...
=> Pin grpcio==1.46.1 (arm64 compatible version available on conda-forge)

src/pudl/output/epacems.py, src/pudl/output/pudltabl.py
A minor simplification of access for the `epacamd_eia` table, since all we do is read it straight from the DB.
=> Simplify EPA CAMD EIA X-walk output to just read from DB.

docker/gcp_pudl_etl.sh
This should make our nightly build slack posts not look silly anymore.
We should merge this as a post-dagster-merge fix to `dev` I think. Not worth the extra hour of waiting for CI before the dagster merge.
=> Fix "Make a PR" link in nightly build success message

src/pudl/workspace/resource_cache.py
We ran into this during nightly builds:
```
The above exception was caused by the following exception:
google.resumable_media.common.DataCorruption: Checksum mismatch while downloading:
https://storage.googleapis.com/download/storage/v1/b/internal-zenodo-cache.catalyst.coop/o/eia923%2F10.5281-zenodo.7236677%2Feia923-2020.zip?alt=media&userP
roject=catalyst-cooperative-pudl
The X-Goog-Hash header indicated an MD5 checksum of:
7IwB5H1MDI+hT3YKRrmGQw==
but the actual MD5 checksum of the downloaded contents was:
w2YhJ2+m55W/tHh5l3/fow==
```
I downloaded the actual file and it had a different checksum from what's in the error:
```
MD5 (eia923-2020.zip) = ec8c01e47d4c0c8fa14f760a46b98643
```
And that matches the md5 listed in the GCP console for …
=> Retry on md5 mismatch in GCS

pyproject.toml
Update to v0.8.2 of our `ferc-xbrl-extractor` package, which allows (but does not require) pandas 2.0, in preparation for addressing #2394 / merging #2320.
=> Use FERC XBRL Extractor 0.8.2 to allow pandas 2.0

docker/gcp_pudl_etl.sh, docker/local_pudl_etl.sh, docs/dev/run_the_etl.rst, pyproject.toml, src/pudl/__main__.py, src/pudl/cli/__init__.py, src/pudl/cli/etl.py, src/pudl/cli/reset_db.py, src/pudl/io_managers.py, test/conftest.py, test/unit/io_managers_test.py, test/unit/reset_db_test.py, tox.ini
Closes #2377 
This makes it so that we don't start with a completely empty DB, we start with one that has the same schema as whatever is written in our `pudl.metadata` package.
This sidesteps the various concurrency issues with trying to make sure the schema is correct *within* the DAG run.
In the future, we might want to use migrations, or have some sort of non-concurrent setup op in the DAG, but for now this will provide a decent UX and hopefully get around the flakiness we've been seeing with the nightly builds (see #2469).
We decided to not use `alembic` for the migrations because of the slightly more complicated UX, but I think using it for diffing schemas is fine and I trust them more than I trust myself, to catch the various edge cases of "does this database setup look right?"
=> Add script to set DB schema before running ETL pipeline

src/pudl/extract/xbrl.py, src/pudl/workspace/datastore.py, test/unit/extract/xbrl_test.py, test/unit/workspace/datastore_test.py
This ensures that are filter values are cast to lowercase so there should not be any issues with incompatible cases used for things like `data_format=XBRL|dbf`.
=> Cast resource filter values to lowercase

src/pudl/transform/ferc1.py, src/pudl/transform/params/ferc1.py
* Fix categorization of `other_total` utility types in DBF data for the `income_statement_ferc1` table so that they end up being `total` rather than `other`.
* Drop the duplicated values of `net_utility_operating_income` that result from that value being reported on both page 1 and page 2 of the old DBF derived income statement form.
=> Fix income_statement_ferc1 utility_type categorization bug

src/pudl/etl/glue_assets.py
Revert EPA-EIA crosswalk to 2018 version until we decide how to handle 2021 version in #2580.
=> Revert crosswalk to 2018

.pre-commit-config.yaml, migrations/versions/9ab4befcc33a_merge_migrations.py, tox.ini
This PR merges together two `alembic` migrations to address the current failure in the nightly builds. It also instructs several pre-commit hooks to ignore any files in the `migrations/` directory. It's probably best to leave the auto-generated files here alone.
=> Merge two 'head' migrations together

devtools/environment.yml
Updates the `pudl-dev` conda environment definition to allow the newly release Jupyter Lab 4.0.0.  I've been using it locally for several days and haven't run into any issues.  [Release notes here](https://jupyterlab.readthedocs.io/en/latest/getting_started/changelog.html#v4-0).
=> Allow JupyterLab v4.0.0 in pudl-dev environment.

src/pudl/metadata/codes.py, src/pudl/transform/eia860.py
Little fix for an operational status code value in the `emissions_control_equipment_eia860` table that was causing the nightly builds to fail. There was a value called "CS" for `plant_id_eia`: 2682, `particulate_control_id_eia` values 9 and 10 in 2016 that wasn't specified in the EIA's list of possible operational status codes. I looked at the operational status codes for the same plant and ids in 2015 and 2017 and both were "RE" so I changed it to RE. 
I made this change in the transform module rather than in the code_fixes part of the CODE_METADATA dictionary because it felt more like a one-off fix then something that should be applied across the board. I.e., I couldn't be sure that future instances of "CS" in the data should be automatically converted to RE.
=> Fix rouge operational status codes causing foreign key failure

docs/dev/run_the_etl.rst
Running through the docs for the first time, and noticed that these names were slightly wrong; this is what they look like for me:
=> Fix job names in docs

src/pudl/workspace/datastore.py
While debugging FERC 2 DBF extraction build failure I found a lingering hard-coded PUDL input directory in the datastore CLI and fixed it.
=> Use PUDL_INPUT not hard-coded data dir in datastore CLI

test/validate/ferc1_test.py
we now have an additional 156 lines from adding calculation corrections into this plant in service table.
this is how i checked what was going on before updating:
```python
from dagster import AssetKey
from pudl.etl import defs, default_assets
table_name = "plant_in_service_ferc1"
pks = pudl.metadata.classes.Resource.from_id(table_name).schema.primary_key
old_df = pd.read_csv(f"{table_name}.csv")
new_df = defs.load_asset_value(AssetKey(table_name))
old_df = old_df.set_index(pks).sort_index()
new_df = new_df.set_index(pks).sort_index()
diff_index = old_df.index.symmetric_difference(new_df.index)
assert(len([c for c in new_df.loc[diff_index].reset_index().ferc_account_label.unique() if "_correction" not in c]) == 0)
```
=> update expected # of plant_in_service rows

src/pudl/extract/eia860.py
This fixes (partially) https://github.com/catalyst-cooperative/pudl/issues/2385, by parallelising the reading in of EIA860 Excel spreadsheets. As suggested in that issue I've largely followed previous work in https://github.com/catalyst-cooperative/pudl/pull/2472 for the implementation.
I've tested this locally with the ETL_FAST job and it seems to work fine.
=> Read EIA860 data in parallel

migrations/versions/e608f95a3b78_drop_amount_from_retained_earnings.py
Looks like we simultaneously pushed two different alembic migration histories into dev and broke the nightly build. Let's fix it!
=> Fix Alembic migration diversions in dev

src/pudl/transform/params/ferc1.py
A few of the column renames in the `utility_plant_summary_ferc1` table appear to have had some cut-and-paste or search-and-replace typos in them, resulting in missing underscores between components of the name.  Unless there's some unusual reason we need not to have those underscores?
=> Fix apparent typos in FERC 1 rename params.

README.rst, docs/data_access.rst
#2665 removed references to pudl@catalyst.coop from datasette. This PR removes pudl@catalyst.coop from a couple of other public-facing pages to discourage folks from emailing pudl@catalyst.coop and instead asking questions on GitHub discussions.
Places `pudl@catalyst.coop` was not removed:
1. `pyproject.toml` and `src/pudl/__init__.py`: I think PyPi gets the email contact information from at least one of these files.
2. `CODE_OF_CONDUCT.md`: If folks need to report inappropriate behavior it should not be public!
3. `src/pudl/metadata/constants.py`, `src/pudl/metadata/sources.py`: I think the zenodo archives pull contact information from these files.
=> Remove pudl@catalyst.coop from docs

src/pudl/transform/ferc1.py
I started with just adding the dfb-only metadata fields into each table's metada doing it in a bespokey way. will probably parameterize this adding of these guys.
=> add straggler dbf-only factoids into ferc1 table metadata

README.rst, docs/data_access.rst
We're [decommissioning the 2i2c JupyterHub](https://github.com/2i2c-org/infrastructure/issues/2607#issuecomment-1577249036) so we need to remove references to it from our documentation.
The PR also moves the increasingly long list of nightly build output links to the Data Access page.
=> Remove refs to 2i2c JupyterHub. Move nightly build links to data access page

src/pudl/output/ferc1.py
i kept in the deletion of the totals in the subdimensions bc i don't forsee us integrating that into the calc forest. its still commented out for now
=> delete it all!!!! lol remove the no-longer needed duplication removals

src/pudl/transform/ferc1.py
This PR follows the same process as the balance sheet assets table for two troublesome components: 
`long_term_portion_of_derivative_instrument_liabilities`, and `long_term_portion_of_derivative_instrument_liabilities_hedges`.
These factoids show up in two calculations: `current_and_accrued_liabilities` and `other_noncurrent_liabilities`. They should be added in `other_noncurrent_liabilities` and subtracted in `current_and_accrued_liabilities` but are currently weighted positively in both. We fix the issues these components cause in the XBRL explosion tree construction and their incorrect calculations by creating new components with the prefix "less_" and replacing them with the original components in the `current_and_accrued_liabilities` calculations, weighted as negative.
=> Fix duplicated components in balance sheet liabilities FERC1 table

src/pudl/analysis/mcoe.py, src/pudl/validate.py, test/validate/mcoe_test.py
- Updates the minmax rows for the mcoe table.
- Extends the upper bounds of acceptable values for gas prices (due to crazy spikes in 2022).
- Removes `inf` values from the fuel cost columns.
We ran some testing on the later to make sure it was a reasonable assumption. Looking at the mcoe table, we tested the fuel cost per mmbtu and mwh (weighted against fuel consumed and net gen, respectively). It shows a definitive bump in 2022:
For mwh:
And for mmbtu:
This is consistent with price hikes in 2022 (largely due to the situation in Ukraine). Shown in mmtbu below:
When looking at the `fuel_recipts_costs` table, you can see that in 2022 the spot market prices were higher than the contracts which is also consistent with expectations.
=> Fix validation errors for 2022 EIA data

.github/workflows/docker-build-test.yml, docker/Dockerfile, pyproject.toml, test/test-environment.yml
* Debug docker build failures that started August 29th see #2836 
* Update `mambaforge` Docker image to a recent version -- we were a year out of date.
* Use Python 3.11 in the base environment in the Docker container.
* Pin `pyarrow<13` for the time being as that introduced the `GLIBCXX` issue.
* Allow a much more recent version of the `google-cloud-sdk` in our test environment.
* Create a `docker-build-test` workflow that runs on `pull_request` to avoid this kind of issue in the future.
=> Fix docker builds

.github/workflows/tox-pytest.yml
To save time/energy/$, we can only run the long CI jobs on PRs that are nominally ready for review.
Testing plan:
=> Skip integraton tests on draft PRs

.github/workflows/tox-pytest.yml, devtools/environment.yml, src/pudl/convert/censusdp1tract_to_sqlite.py, test/test-environment.yml
Something is suddenly breaking our use of `ogr2ogr` in a subprocess to extract the Census DP1 GeoDataBase, but only in CI not locally. This PR is an attempt to debug why.
* Update `tox-pytest` workflow to use `setup-micromamba` and `checkout@v4`
* Add some assertions about the inputs & output paths involved in running `ogr2ogr`
=> Add assertions and workflow updates to debug ogr2ogr failure.

src/pudl/helpers.py, test/integration/ferc_dbf_extract_test.py
This is just me being a little bit OCD.
* Added type hints to all remaining functions in pudl.helpers that didn't have them.
* Added schema compatability checks for FERC 6 and 60 DBF derived SQLite DBs.
* Use a context manager when dropping tables in `pudl.helpers.drop_tables()`
=> Add type hints to helpers and update DBF extraction tests

src/pudl/metadata/constants.py, src/pudl/metadata/sources.py
Addresses #2850 and [issue #80 in the pudl-archiver repo](https://github.com/catalyst-cooperative/pudl-archiver/issues/80). The lack of keywords is a blocking issue for PHMSA data extraction using the pudl Datastore, so this iceboxed issue is now a priority again. While I'm at it, I may as well fix all the other datasets that are missing keywords / have inadequate ones.
=> Fix missing keywords in archived datasources

devtools/environment.yml, test/test-environment.yml
A new patch version `gdal==3.7.2` and a new minor version `geopandas==0.14.0` have been released, potentially fixing this linking error? Let's find out.
=> Remove libabseil version pins since gdal & geopandas have new versions.

src/pudl/metadata/sources.py, src/pudl/transform/params/ferc1.py
Subset of issues in #2813, fixing errors introduced in the 2022 runthrough of FERC1 data through the new XBRL extractor.
=> Fixing 2022 FERC ETL integration errors

src/pudl/output/ferc1.py
found duplicate tables names in the inputs for the explosions. this pr removes them!
```
income_statement_ferc1: has 5061 (18.15%) records whose calculations don't match. Adding correction records to make calculations match reported values.
balance_sheet_liabilities_ferc1: has 226 (6.91%) records whose calculations don't match. Adding correction records to make calculations match reported values.
balance_sheet_assets_ferc1: has 12021 (59.93%) records whose calculations don't match. Adding correction records to make calculations match reported values.
```
```
income_statement_ferc1: has 5061 (18.15%) records whose calculations don't match. Adding correction records to make calculations match reported values.
balance_sheet_liabilities_ferc1: has 226 (6.91%) records whose calculations don't …
```
=> remove duplication of explosion input table names

devtools/environment.yml, docs/docs-environment.yml, test/test-environment.yml
Remove the `python-snappy` dependency from our conda environments, since it no longer seems to be a requirement for working with snappy compression in Apache Parquet files. PyArrow/Parquet now uses snappy compression by default and it seems like they're statically linking or re-implementing libsnappy rather than requiring it to be installed on the user's system (which seems great).
=> Remove libsnappy binary dependency

pyproject.toml
Apparently an issue in the packaging of `croniter==2.0.0` is causing `mamba` to crash with an `AssertionError` after the package is installed in a conda environment with `pip` so we need to pin to `croniter<2` See https://github.com/kiorky/croniter/issues/54
Also it seems that the dynamic library linking problem that we were having with `pyarrow==13.0.0` has been resolved so removing that pin.
=> Pin transitive dependency croniter<2; bump pyarrow to v13

src/pudl/output/ferc1.py
The nightly build was breaking for the `exploded_balance_sheet_assets_ferc1` asset, due to having too many paths between a particular root node & leaf node. Now the asset builds, at least on *my* machine. I don't believe there are validation tests affected by this change.
After talking with @zaneselvans we decided that we could handle multiple paths, and only raise an error if the paths conflict.
Not in scope:
* renaming the `forest` stuff since we don't have a forest anymore - maybe call it `digraph` or `dag`?
Maybe in scope / maybe a good follow-on PR:
* writing some unit tests - this calc graph stuff seems like a pretty good candidate for property based testing.
=> Fix too-many-paths error in nightly build

pyproject.toml
Unpin `croniter` as the package metadata bug has been fixed in version 2.0.1.
See https://github.com/kiorky/croniter/issues/54
=> Unpin croniter as package metadata has been fixed.

src/pudl/workspace/datastore.py, test/unit/settings_test.py, test/unit/workspace/datastore_test.py
Closes #2939 .
* Use new record files API endpoint to get datapackage.json
* Add shim to re-construct legacy URLs that are in `datapackage.json` / pretend that we were using the "best, most stable URLs" the whole time
* remove access keys, yay
=> New zenodo api bandaid

docker/Dockerfile
For some reason, `pudl_setup` and other tools would not properly link with libraries provided by conda and living in `/home/catalyst/env/lib`. This sets the path so that linker correctly finds those things as per:
https://stackoverflow.com/questions/13428910/how-to-set-the-environment-variable-ld-library-path-in-linux
=> Hotfix docker build by setting LD_LIBRARY_PATH

test/unit/io_managers_test.py
Some non-printable characters seem to break Pandas groupby, which was causing the test to mis-identify which contexts were worth making assertions about.
=> Only generate alphanumeric entity IDs in test

src/pudl/metadata/fields.py, src/pudl/transform/ferc714.py
For some reason `report_date` could be missing for some number of records (0.7%). This addresses that problem by changing the way we align the reports to year boundaries.
=> Fix calculating the report_date in demand_hourly_pa_ferc714

test/unit/io_managers_test.py
See this failure, which is due to slow strategies: https://github.com/catalyst-cooperative/pudl/pull/2968#issuecomment-1788120124
We already know that pandera strategy generation is slow - combining that with the slowness of generating strings based on regex was too much I think.
=> Switch regex strategy to sampling strategy to improve performance

.github/workflows/build-deploy-pudl.yml
This PR adds the `build-deploy-pudl.yaml` workflow from #2996 to `main` so scheduled `dev` builds use the updated file.
=> Add dagster postgres env vars to build-deploy-pudl.yaml

src/pudl/analysis/classify_plants_ferc1.py, src/pudl/output/ferc1.py
We were getting the following error:
```python
FAILED test/validate/fbp_ferc1_test.py::test_fbp_ferc1_mismatched_fuels[ferc1_annual] - AssertionError: Too many records (9.69%) have mismatched primary fuel types.
```
I determined that this was happening bc the nulls in the fuel table were somehow getting converted to `"nan"`:
A part of the `pudl.analysis.classify_plants_ferc1.fuel_by_plant_ferc1` step does convert nulls to `""` and there is a post-processing step that we were already applying (`pudl.analysis.classify_plants_ferc1.revert_filled_in_string_nulls`). I simply added `"nan"` in here.
Still tbh do no know why these `"nan"`s were all of a sudden appearing but hey.. they are gone now 👀 
it looooks as if the "nan" is added in right here...
```python
for fuel_str in fuel_categories: …
```
=> Fix validation `test_fbp_ferc1_mismatched_fuels` error

test/unit/io_managers_test.py
If the DB schema as defined in `metadata.classes.Package.from_resource_ids()` doesn't match the schema you get from running `alembic upgrade head`, **AND** `PudlPaths().pudl_db` is a pre-existing file, the `pudl_sqlite_io_manager` throws an error at startup.
HOWEVER!
1. in integration tests, when `pudl_sqlite_io_manager` is initialized, `PudlPaths().pudl_db` does not actually point to an existing file, so we use `metadata.create_all()` - which masks any differences between the migrations and the Package
2. in nightly builds, the `pudl_sqlite_io_manager` isn't initialized until we actually want to write to the DB, which is pretty late in the DAG execution. This is a super avoidable nightly build failure.
So, to catch any divergence between the alembic migrations and the package metadata, I …
=> Test that DB schema matches the Alembic migrations

docs/dev/naming_conventions.rst, docs/release_notes.rst, src/pudl/output/pudltabl.py
This PR:
- Adds information about the name change to the release notes
- Adds deprecation warnings to `PudlTabl`
- Explains why schedule numbers are in the ferc names
- Adds our policies about ordered source names in association table names and when to use `pudl` as a source
=> Add naming convention change to release notes

notebooks/work-in-progress/CEMS_by_utility.ipynb, notebooks/work-in-progress/better-heatrates.ipynb, notebooks/work-in-progress/ferc714-output.ipynb, notebooks/work-in-progress/jupyterhub-test.ipynb, notebooks/work-in-progress/state-demand.ipynb, src/pudl/extract/xbrl.py, src/pudl/io_managers.py, src/pudl/workspace/setup.py, test/unit/extract/xbrl_test.py, test/validate/notebooks/validate_bf_eia923.ipynb, test/validate/notebooks/validate_fbp_ferc1.ipynb, test/validate/notebooks/validate_frc_eia923.ipynb, test/validate/notebooks/validate_fuel_ferc1.ipynb, test/validate/notebooks/validate_gens_eia860.ipynb, test/validate/notebooks/validate_gf_eia923.ipynb, test/validate/notebooks/validate_mcoe.ipynb, test/validate/notebooks/validate_plants_steam_ferc1.ipynb
On dev, if you set `clobber: True` in the `ferc_to_sqlite` job config, it will clobber the existing database when extracting 2021 data, and then clobber it again when extracting 2022 data.
* clobbering happens on PUDL side now, instead of on ferc-xbrl-extractor side - so it gets called once per op instead of once per form
* you can still clobber when running ferc-xbrl-extractor on its own
This was *probably* the cause of the missing 2021 XBRL data that @cmgosnell ran into yesterday.
=> Fix XBRL extraction clobber

test/unit/extract/xbrl_test.py
The unit tests running with `--live-dbs` actually clobbered the XBRL databases - so we'd generate them, run ETL based on them, and then clobber them in nightly build before we got to actually upload to GCS.
=> Always use tmp path for clobber tests.

.gitattributes
I'm still getting merge conflicts between environment files. I don't think the merge strategy is working because it's looking for .yaml files instead of .yml files.
=> Change lock file merge strategy to look for .yml instead of .yaml files

docs/conf.py, docs/dev/dev_setup.rst
- Replace `black` autoformatting instructions with `ruff`
- Include a note that you need to run `git config` to get nice conda lockfile merges.
- Make PUDL conda environment setup instructions less confusing.
=> Update development setup documentation

.github/workflows/update-conda-lockfile.yml, Makefile, docs/dev/dev_setup.rst, environments/conda-linux-64.lock.yml, environments/conda-lock.yml
Some small improvements to the ergonomics of setting up the `pudl-dev` conda environment, especially for the first time:
* Use `make` to install `conda-lock` and `prettier` in the user's base conda environment using `mamba run`, rather than requiring it to be done manually. This means the only setup requirements are `mamba` and `make`.
* Remove the make dependency that was causing many first-time environment installations to also rebuild the `conda-lock.yml` file -- that will get taken care of automatically in CI if need be (because `pyproject.toml` or other dependency files were changed).
* Update dev setup docs to reflect this simplification.
* Add `Makefile` to the list of paths that triggers a rebuild of the conda lockfile... since it affects the process.
=> Simplify process of bootstrapping pudl-dev conda env.

src/pudl/workspace/setup.py
When I tried to run `make docs-build`, I would get a validation error from `PudlPaths()`:
```
exception: 1 validation error for PudlPaths                                                                                                       
dagster_home                                                                                                                    
Extra inputs are not permitted [type=extra_forbidden, input_value='/Users/dazhong-catalyst/work/dagster_home', input_type=str]
For further information visit https://errors.pydantic.dev/2.5/v/extra_forbidden
```
This happened because my `pudl/.env` file contains:
```
PUDL_OUTPUT=/Users/dazhong-catalyst/pudl_workspace/output
PUDL_INPUT=/Users/dazhong-catalyst/pudl_workspace/data …
```
=> dotenv compatibility

.github/workflows/build-deploy-pudl.yml, .github/workflows/release.yml
- Sets up a workflow to do GitHub (and possibly PyPI) releases automatically any time a tag is pushed starting with `v20` (matching calendar versions like `v2023.12.05` for the next 77 years).
- This includes a new job that attempts to build valid source & binary (wheel) distribution of the repo on every push, creating the files which would then be distributed if the right tag is pushed to `main`
- The publication of a GitHub release triggers the archiving of the PUD **repository** on Zenodo (through the GitHub-Zenodo integration app we have set up already), which is one of the goals of the automated releases. See #2756 
- We already have a build-on-tag action set up. The data release work (creating a new **data** archive on Zenodo, pushing to persistent locations on GCP/S3) will be done …
=> Add GHA workflow for release-on-tag

.github/workflows/update-conda-lockfile.yml, .pre-commit-config.yaml
Closes #3133.
We introduced `conda-lock` and lockfiles in an attempt to avoid instability caused by frequent dependency version changes. 
However, we have been re-locking very eagerly, which means that we are actually still very susceptible to dependency version changes that break our ETL. It also chews through our CI budget.
At least it's very easy to see what changed in the environment between runs!
So we decided to only re-lock:
* before committing a change to `pyproject.toml`
* once a week
This adds a simple hook to `.pre-commit-config.yaml` which runs our re-locking `make` command when `pyproject.toml` changes.
If `pyproject.toml` doesn't change, the hook is skipped; if `pyproject.toml` changes, it runs `make conda-clean conda-lock.yml`.
If `make` doesn't actually change any of the …
=> Update lockfiles on pre-commit

devtools/zenodo/zenodo_data_release.py, docker/gcp_pudl_etl.sh
Just struggling with the Zenodo API for the moment. Can easily do a manual upload of the files as well.
=> Script to sync a local directory up to a Zenodo DOI

.github/workflows/build-deploy-pudl.yml, docker/gcp_pudl_etl.sh, environments/conda-linux-64.lock.yml, environments/conda-lock.yml, environments/conda-osx-64.lock.yml, environments/conda-osx-arm64.lock.yml
Attempt to create a sandbox data release after the nightly builds succeed.  This is just meant to test the data release publication process until we switch over to creating real releases from tagged builds.
I think the workflow needs to be added to `main` before it'll work in the scheduled builds though.
I added the `ZENODO_SANDBOX_TOKEN_PUBLISH` to the organization secrets.
=> Attempt to create sandbox data release in nightly builds.

.github/workflows/build-deploy-pudl.yml
Try to fix `COMMIT_BRANCH` calculation (doesn't work) and use runtime timestamp instead of commit timestamp when constructing the output name.
=> Alter output path for the nightly builds

src/pudl/etl/__init__.py, src/pudl/etl/cli.py, src/pudl/helpers.py
#3096 limited concurrency for the `hourly_emissions_epacems` asset for the jobs being loaded into the `dagster-webserver`. This PR applies the limit to the `pudl_etl` command. 
I ran into an OOM issue when running a full build on the `rename-core-asset` branch. We haven't run into this issue yet on a nightly `dev` build which is a little suspicious. Maybe we've just been getting lucky on `pudl-deployment-dev`? I diffed the tag and dev machines specs and they are working with the same amount of CPUs and memory. Either way, I think we should be able to limit CEMS concurrency for the `pudl_etl` command.
I ran `pudl_etl` locally and made sure only two partitions were executed at once.
```[tasklist]
```
=> Add EPA CEMS concurrency limit to `pudl_etl`

README.rst, docs/data_access.rst
* Removed obsolete references in the README to using Docker containers + Jupyter locally to access data.
* Added pointers to Kaggle and Zenodo instead.
```[tasklist]
```
=> Remove obsolete Docker data access instructions.

.github/release.yml, .github/workflows/build-deploy-pudl.yml, .github/workflows/docker-build-test.yml, .github/workflows/pytest.yml, .github/workflows/release.yml, docker/Dockerfile, docker/gcp_pudl_etl.sh
- Remove minor versions from the GHA we depend on to minimize dependabot churn.
- Remove the logic that was updating conda lockfiles on push.
- Purge old files from distribution paths before uploading new outputs. This prevents stale files from hanging around after we change the name of a file.
- Tag commits that are used for nightly builds.
- Update `stable` branch to point at newly tagged release
- Update `nightly` branch to point at newly successful nightly build tag.
- Simplify Dockerfile / make it more internally consistent
- The nightly build jank continues. We need to dedicate some resources to consolidating it!
Part of #3140
=> Improve nightly build and deployment logic

.github/workflows/build-deploy-pudl.yml, docker/gcp_pudl_etl.sh
Takes the working elements of #3183 and gets them merged into `main` so the builds are working again.
- Fix syntax error in build-deploy-pudl workflow.
- Move envvar printing into separate step
- Rename GITHUB_REF to BUILD_REF
- set the nightly tag, so we have something to merge
- Allow write permissions for git tagging in nightly builds workflow
- Functionalize udpate_nightly_branch()
- Set origin for nightly when pushing.
- Temporarily disable nightly branch updates to fix nightly builds.
=> Clean up nightly build/deploy w/o nightly branch update.

src/pudl/workspace/datastore.py
Closes #3186.
We had to make a new zenodo archive with eia860m a years worth of monthly files zipped together into one resource because *file upload limits*. So this pr 
basically nothing except the DOI. bc @e-belfer added a little logic into the datastore to work with partitions that are lists of partitions. And the excel extractor/the datastore combined  already knows how to grab a file out of a zipped file bc of course it does bc so many of our one partition resources have many files. The main place where this is happening is `load_excel_file`.
We could remove the first `try` in `load_excel_file` because the old eia860m archive being individual files was actually the edge case.
How did you make sure this worked? How can a reviewer …
=> update the 860m doi

pyproject.toml
Update configuration for `setuptools_scm` such that it only considers tags matching `v20*` when trying to determine the current version.
Related to #3140
After altering `pyproject.toml` I attempted to install the PUDL package using `pip`
```[tasklist]
```
=> Tell setuptools_scm to ignore non-version tags

src/pudl/analysis/eia_ferc1_record_linkage.py, src/pudl/analysis/record_linkage/classify_plants_ferc1.py
Addresses `nightly-2023-12-27` build failure by:
- lowering expected consistency between FERC-FERC and FERC-EIA entity matching from 75% to 74%.
- documents what's being checked in the assertion that was failing.
- also makes implicit weights of 1.0 explicit in the FERC 1 plant classification pipeline.
Ran the full ETL locally.
```[tasklist]
```
=> Clarify consistency check and lower threshold from 75% to 74%

test/integration/record_linkage_test.py
- Reduce FERC1 match threshold in test to 85%
Closes #3196
```[tasklist]
```
=> Reduce FERC1 match threshold in test to 85%

environments/conda-linux-64.lock.yml, environments/conda-lock.yml, environments/conda-osx-64.lock.yml, environments/conda-osx-arm64.lock.yml
=> Update conda lockfile for week of 2024-01-01

.github/workflows/build-deploy-pudl.yml
Follow-up to #3195 ; Related to #3140 .
We were getting inconsistent behavior pulling the latest image for a certain tag off of Dockerhub - often we would get an out-of-date image running on the VM.
While investigating Google Batch, I found that this was due to Dockerhub not updating its tag references quickly enough. However, we can just refer to the actual image digest we just built, which is unambiguously the correct image.
Given how small this change is, I decided to pull this logic over to the non-Batch world as well, so we don't have to wait for me to get all the Batch stuff working.
I short-circuited `gcp_pudl_etl.sh` and had it echo a short message to the logs.
Then:
1. change the line
2. push
3. run `build-deploy-pudl.yml`
4. observe that the output includes the changed line! …
=> Use digest instead of tag so VM uses right image.

src/pudl/logging_helpers.py
This PR explicitly sets the `numba` loglevel to avoid excessive debug logs.
=> Suppress excessive numba logs

.github/workflows/release.yml, docs/conf.py, src/pudl/metadata/classes.py, src/pudl/metadata/codes.py, src/pudl/metadata/fields.py, src/pudl/metadata/resources/eia.py, src/pudl/metadata/resources/pudl.py, test/integration/output_test.py, test/unit/metadata_test.py
Previously, we were unable to use the `Resource.to_pyarrow()` method to generate PyArrow schemas for all of our tables, and had historically only used it for the billion-row EPA CEMS table. It turns out that the issues preventing the schemas for being valid were minor and easy to fix:
- Some tables and fields were missing a `description` field, which we were assuming would be present and trying to write into the Parquet metadata.
- Some tables and fields don't have a `primary_key` but we were assuming one always existed, and trying to write that into the Parquet metadata as well.
- I added a few missing titles / descriptions and also added a conditional that uses an empty string if the description is `None`.
- I added a conditional that only writes the `primary_key` to the Parquet …
=> Tweak metadata and pyarrow schema methods to work for all tables

devtools/datasette/publish.py
Closes #3229 .
We had what appeared to be a transient issue while deploying to fly.io. To test that out, I wanted to try running the Docker build on the `fly.io` builders, since that was the failing step. `flyctl deploy` provides this functionality, so I added the `--build-only` flag to our `publish.py` to configure that behavior.
I ran this with the `--build-only` and checked on https://fly.io/apps/catalyst-coop-pudl/activity for any new releases. No new releases, but I did get a "finished building docker image" log from `flyctl`. So that seems like it works!
```[tasklist]
```
=> Add --build-only flag to datasette deploy script.

notebooks/.gitignore, notebooks/local/README.md
I have some untracked local notebooks that probably don't belong in git but are still things I'd like to save. This PR creates a new directory called `notebooks/local/` that only contains a `.gitignore` file so folks can stash old notebooks in their pudl directory but not have them tracked in git.
```[tasklist]
```
=> Create directory for local only notebooks

devtools/debug-ferc1-etl.ipynb, src/pudl/workspace/datastore.py
Update to a fresh EIA Bulk Electricity data archive so that fuel price estimates run through most of 2023.
Existing EIA bulk electricity data was only available through mid 2022. Somehow we failed to update in 2023!  Gaby from RMI asked whether the new data could be made available so I created a new archive (which [had some issues](https://github.com/catalyst-cooperative/pudl-archiver/issues/256)... but in the end seemed to work.)
- Updated the EIA Bulk Electricity data input archive DOI.
- Ran integration tests locally
- Ran a full ETL locally, and this bumped the date of the last filled fuel price from 2022-06-01 to 2023-08-01.
```[tasklist]
```
=> Update EIA bulk electricity data archive.

docs/release_notes.rst, src/pudl/validate.py, test/validate/mcoe_test.py
- Bumped the upper bound on natural gas prices per MMBTU to accommodate the integration of the new EIA Bulk Electricity data, which includes more high prices from 2022.
- Found an XPASSing test related to using the allocated fuel in MCOE which... should actualy be passing, so removed the XFAIL mark.
Closes #2033 
Closes #3250 
Re-ran the failing tests with `--live-dbs` locally on my full ETL outputs locally and they passed.
```[tasklist]
```
=> Update gas price upper bound; Enable null-row check for MCOE.

.github/workflows/build-deploy-pudl.yml, .github/workflows/release.yml, devtools/zenodo/zenodo_data_release.py, docker/gcp_pudl_etl.sh, docs/data_access.rst, docs/dev/index.rst, docs/dev/run_a_release.rst
Closes #3175:
- Tries to upload draft to Zenodo prod
- Doesn't run PyPI release unless test PyPI release goes through
- added docs
Side-note:
It *really* doesn't seem like it would be that hard to grab the outputs from GCS & just upload to Zenodo that way:
- use `git tag --points-at {{ github.ref_name }}` to figure out which nightly build to access on `builds.catalyst.coop`
- auth into GCP - we could add another WIF identity, or just use the one we use in `build-deploy-pudl.yml`
- sync the directory down to some location on the runner
- check out repo + install deps
- run zenodo_data_release.py
Some clean-up we'd have to do:
- stop running build-deploy-pudl on tag
- run `release.yml` on pushes to `nightly` as well as `vYYYY.MM.DD`, with the appropriate conditionals (e.g., never running …
=> Push to prod Zenodo sometimes, fix pypi release flow, update docs

src/pudl/metadata/sources.py
A subset of the archiver changes tracked in https://github.com/catalyst-cooperative/pudl-archiver/issues/262.
Adds EIA Forms 191 and 757, which are both available from the EIA NGQS, to PUDL metadata so we can archive (and then integrate) them.
Added metadata for these two forms into `pudl.metadata.sources.py` based on information available [here](https://www.eia.gov/Survey/index.php) and PDF instructions for each form.
```[tasklist]
```
=> Add EIA Forms 191 and 757 to sources in PUDL metadata

.github/workflows/build-deploy-pudl.yml
Closes #3320 .
The `BUILD_REF` env var wasn't being set correctly ([GHA logs](https://github.com/catalyst-cooperative/pudl/actions/runs/7706962258/job/21003361867)), which lead to the nightly build not publishing any of last night's outputs.
I set it to the `github.ref_name` value which worked for `nightly-2024-01-27`. 
We can kick off an ad-hoc run with workflow_dispatch and verify that BUILD_REF is indeed being set properly.
```[tasklist]
```
=> Update build ref

devtools/generate_batch_config.py, docker/gcp_pudl_etl.sh
Closes #3328
Fixes issues surfaced in the build failure for 2024-01-31
- Increase Google Batch instance memory to 64GB
- Fix a Slack notification formatting error so we can see the `$BUILD_ID`
- The actual build failure (Locked SQLite DB) seems like it's probably stochastic and can hopefully be ignored
- pulled the postgres shutdown command out of the chained PUDL ETL command so it's run no matter what happens in the ETL.
```[tasklist]
```
=> Fix nightly builds 2024-01-31

src/pudl/helpers.py
Closes #3333.
full error over in #3333
we got a `cannot reindex on an axis with duplicate labels` error from this line:
```
File \"/home/mambauser/pudl/src/pudl/helpers.py\", line 1516, in weighted_average
df[\"_weight_where_notnull\"] = df.loc[df[data_col].notnull(), weight_col]
```
basically just used a df.loc[mask] on both sides of the assign inside of just one.
```[tasklist]
```
=> Fix nightly build failure on EIA plant parts asset reindex problem.

.github/workflows/docker-build-test.yml, .github/workflows/pytest.yml
Closes #3317.
This makes our PR checks also run on merge_group triggers, so that our required checks can actually pass when PRs are added to the merge queue.
We'll have to turn on the merge queues & test it out manually.
```[tasklist]
```
=> Trigger CI on merge group; only trigger integration on merge group.

.codecov.yml, .github/pull_request_template.md, .github/workflows/pytest.yml, pyproject.toml
CodeCov v4 demands a token to upload data to their service. Even though we are a public repo.  So we will given them a token. Even though the token is already in our `.codecov.yml` I guess we should remove it.
```[tasklist]
```
=> Provide CodeCov token in pytest workflow.

test/conftest.py, test/unit/conftest.py, test/unit/extract/xbrl_test.py
Closes #3376 .
When merging #3098 we ended up merging a change that inadvertently clobbered the XBRL SQLite DBs in unit test, when `--live-dbs` was passed. This is not the first time tests of our clobbering logic have actually clobbered our hard-won data.
Make it so that the unit tests have their own conftest.py which ignores `--live-dbs`. Unit tests should never rely on live dbs, ever, so let's make that impossible.
Ran the unit tests with `--live-dbs` on `main` and saw it clobber all my XBRL dbs; then `touch $PUDL_OUTPUT/ferc1_xbrl.sqlite` etc and re-ran the unit tests on this branch, with `--live-dbs`, and saw that the DBs survived unscathed.
```[tasklist]
```
=> Stop using live DB in unit tests!!

docker/gcp_pudl_etl.sh
Since we don't run docs build in nightly, coverage is necessarily lower and fails our thresholds.
Closes #3381.
We added a "fail-under" threshold to our coverage configuration - which is useful to capture coverage drops. But, since we don't build the docs in nightly build, our unit/integration tests will always fail that threshold, thus failing the build.
We already calculate the coverage in CI, we don't need to do it in the nightly build.
Alternatives:
- build docs in nightly build also
- set `--cov-fail-under=0` which effectively stops us from failing the threshold, but also is more confusing
I'm going to run a build on this branch via GHA and see if we still fail on coverage.
```[tasklist]
```
=> Force --no-cov in nightly build

src/pudl/convert/censusdp1tract_to_sqlite.py, src/pudl/extract/dbf.py, src/pudl/extract/eia176.py, src/pudl/extract/epacems.py, src/pudl/extract/excel.py, src/pudl/extract/ferc714.py, test/integration/etl_test.py
Hopefully, using context managers to close connections to zip files will resolve our sporadic `BadZipFile` error #3364.  
```[tasklist]
```
=> Use context managers for opening zipfiles

README.rst, docs/data_access.rst, docs/release_notes.rst, src/pudl/metadata/sources.py, src/pudl/workspace/datastore.py
Closes #3315 
Adds Q4 2023 CEMS data.
Added Q4 data to extraction, updated docs.
Materialize the EPA CEMS dagster assets.
```[tasklist]
```
=> Add Q4 CEMS data

.github/workflows/build-deploy-pudl.yml
The [2024-02-11](https://github.com/catalyst-cooperative/pudl/actions/runs/7860068155) and [2024-02-12](https://github.com/catalyst-cooperative/pudl/actions/runs/7867868547) builds were skipped, but we didn't get a Slack notification because the GHA itself failed.
We had forgotten to skip the "kick off a batch job" step when the build was skipped, so it was trying to do that, failing, and then not sending any notification.
I added the skip condition + force the slack notif to always run.
We'll see if it works the next time we have a skip!
```[tasklist]
```
=> Skip batch job if build was skipped as a whole.

docker/gcp_pudl_etl.sh
Distribute parquet outputs to a private bucket using the same path conventions that we're using in the public buckets for the other outputs.
Closes #3362 
I wish there were an easy way to test this besides running the nightly builds and having them fail repeatedly.
```[tasklist]
```
=> Update nightly build script to distribute parquet

environments/conda-linux-64.lock.yml, environments/conda-lock.yml, environments/conda-osx-64.lock.yml, environments/conda-osx-arm64.lock.yml
=> Update conda lockfile for week of 2024-02-26

.github/ISSUE_TEMPLATE/versioned_release.md, docker/gcp_pudl_etl.sh
Address the minor issues that came up in #3360
- Re-order some of the release checklist, and add a task to verify Parquet release outputs are okay
- Fix the command that puts a hold on release outputs so they can't be deleted accidentally.
```[tasklist]
```
=> Fix minor issues that arose in v2024.2.6 release

src/pudl/workspace/datastore.py
Added the new DOI for the EIA Thermoelectric Cooling Water dataset to the PUDL datastore, since it's available for download now, even though we haven't started processing it yet.
I ran
```console
pudl_datastore -d eiawater
```
and it successfully downloaded all years of EIA water spreadsheets.
```[tasklist]
```
=> Add EIA Thermoelectric Cooling Water dataset DOI to datastore.

docs/catalyst_cites.bib
Add a citation to a report on resurgent US electricity load growth which relied on PUDL data.
I built the docs locally and looked at the bibliography page and all was good.
```[tasklist]
```
=> Add PUDL citation for Grid Strategies load growth report.

src/pudl/workspace/datastore.py
Related to #3453 .
We keep getting these BadZipFile errors but don't really have much to go on - so we should log out some information about the ZipFiles.
Add a logline.
Ran `raw_phmsagas__all_dfs` asset in dagster and verified that these logs showed up in the terminal:
```
2024-03-21 16:45:22 [    INFO] catalystcoop.pudl.workspace.datastore:425 Got resource dataset='phmsagas', filters={'year': 2008, 'form': 'gas_distribution'}, md5sum='4ef276c35808fd8ea0feddf6e2881511', 8513846 bytes; turning into ZipFile    
```
=> Add logline that tells us more about BadZipFile.

test/validate/ferc1_test.py
these two new records are a result of adding corrections when either the reported or calculated value is null. this change did not add a ton of extra records to a ton of tables because most of the tables that get their calculations reconciled/corrected are not the orignal ferc1 tables that are in the PudlTabl. These calculation-reconciled tables are mostly new and are mostly not being tested in our test_minmax_rows tests.
- fixes a nightly build failure introduced via #3450
i used the `sqlite-table-diff` notebook to ensure that the two new records are indeed correction records. also verified that there were no unexpected other changes in this table
```[tasklist]
```
=> add two new correction records into plant_in_service table

CONTRIBUTING.rst, src/pudl/etl/__init__.py
This changes how we add new modules to the ETL so we only have to add them in one place. Also it organizes them slightly.
Finally, there's a tiny opportunistic change to the docs to remove a reference to `dev`.
* Checked to see that all modules on the left do indeed show up on the right.
* Loaded up Dagster UI and saw that the ETL appears to still be there
```[tasklist]
```
=> Refactor etl/__init__.py to make adding new modules easier.

src/pudl/analysis/plant_parts_eia.py, src/pudl/analysis/record_linkage/eia_ferc1_record_linkage.py, src/pudl/analysis/state_demand.py, src/pudl/etl/__init__.py, src/pudl/etl/cli.py, src/pudl/etl/epacems_assets.py, src/pudl/extract/gridpathratoolkit.py, src/pudl/output/ferc714.py, src/pudl/transform/eia860m.py, src/pudl/transform/gridpathratoolkit.py
Closes #3533.
Attempts to limit max concurrency to 1 when the `_out_ferc714__hourly_demand_matrix` asset is running in an attempt to reduce memory usage on the nightly build VM. 
I'm still a little confused about how dagster's concurrency limiting with tags works, see me [comment here](https://github.com/catalyst-cooperative/pudl/issues/3533#issuecomment-2035791127).
Also, if we keep needing to limit concurrency when certain assets are run because of memory issues, we should come up with a more generalization method so we can restrict the concurrency for any asset. This PR just adds some hard coded values to the an asset decorator and the ETL scripts.
```[tasklist]
```
=> Attempt to limit `_out_ferc714__hourly_demand_matrix` concurrency

.github/workflows/build-deploy-pudl.yml, src/pudl/analysis/record_linkage/classify_plants_ferc1.py, src/pudl/analysis/record_linkage/eia_ferc1_record_linkage.py, src/pudl/analysis/record_linkage/link_cross_year.py, src/pudl/analysis/state_demand.py, src/pudl/etl/__init__.py, src/pudl/etl/cli.py, src/pudl/extract/extractor.py
This PR follows on #3541 
* Tag additional high memory (>4GB peak) processes
* Dial down the parallelism of Numpy's linear algebra
* Increase the allowed concurrency of high memory processes, since we can be more confident about limiting their overall number with more complete tagging.
The nightly build machine has no swap, and 4GB of memory per CPU (16 CPUs, 64 GB of memory, as on all "highmem" instances). Some of the assets in our DAG use significantly more memory that that, and sometimes a few of them stack on top of each other and they run out of memory, crashing the process and causing the ETL to fail.
After a lot of time running individual assets and watching the per-process memory consumption while the ETL was running locally, it seems like there aren't *that* many assets / ops …
=> Manage concurrency of high-memory processes

environments/conda-linux-64.lock.yml, environments/conda-lock.yml, environments/conda-osx-64.lock.yml, environments/conda-osx-arm64.lock.yml
Relocking because we've currently locked a version `jaraco.context==5.3.0` which got marked as broken due to some changed dependencies. see [this PR](https://github.com/conda-forge/jaraco.context-feedstock/pull/8)
=> Update lockfile to avoid yanked version of jaraco.context

docs/release_notes.rst, src/pudl/io_managers.py, src/pudl/transform/params/ferc1.py, test/unit/io_managers_test.py
Closes #3309.
A bunch of utilities sent diff-only reports to update their 2021 data, which led to some important XBRL tables being mostly-null.
After much debate and investigation, we decided to change the XBRL deduplication to take the latest non-null value (across multiple filings) instead of taking the value from the latest single filing.
@cmgosnell I'd love if you could take a look and see if this affects rate base table in the expected way.
```[tasklist]
```
=> Get last non-null value instead of latest XBRL filing.

src/pudl/extract/csv.py, src/pudl/extract/eia930.py
Previously almost all numerical columns in the EIA-930 extraction were appearing as type object because in the CSV they show up as quoted strings with commas separating every 3 digits.
This PR ensures that those columns are parsed as numbers, and the datetime columns are parsed as datetimes when the CSVs are first read in, dramatically reducing overall memory usage, and avoiding the need to deal with enormous untyped dataframes in the transform steps.
```[tasklist]
```
=> Parse EIA-930 CSVs during extract to minimize memory use

environments/conda-linux-64.lock.yml, environments/conda-lock.yml, environments/conda-osx-64.lock.yml, environments/conda-osx-arm64.lock.yml
=> Update conda lockfile for week of 2024-04-22

terraform/main.tf
1. Adds a few beta users for our parquet access.
2. Updates our google storage permission configuration to match the manually-added folks.
How did you make sure this worked?
Ran `terraform plan` and saw that we added two SA's, renamed one, and no other changes were planned.
```
random_id.bucket_prefix: Refreshing state... [id=80QeQV5uXn0]
module.gh_oidc.google_iam_workload_identity_pool.main: Refreshing state... [id=projects/catalyst-cooperative-pudl/locations/global/workloadIdentityPools/gh-actions-pool]
google_service_account.service_account: Refreshing state... [id=projects/catalyst-cooperative-pudl/serviceAccounts/rmi-beta-access@catalyst-cooperative-pudl.iam.gserviceaccount.com]
google_storage_bucket_iam_binding.binding: Refreshing state... …
```
=> Create beta access SA's for gridpath and zerolab.

terraform/main.tf
I forgot to actually give the beta service accounts any permissions in #3577 .
Did that ^
`terraform plan` output: 
```
Terraform will perform the following actions:                                                                                   
~ resource "google_storage_bucket_iam_binding" "binding" {                                                                    
id      = "b/parquet.catalyst.coop/roles/storage.objectViewer"                                                          
~ members = [                                                                                                             
+ …
```
=> Allow beta service accounts to access Parquet bucket

.pre-commit-config.yaml
I finally got fed up waiting several seconds for `nb-output-clear` to do its thing and made it only clear ipynbs that actually changed.
1. made some trivial changes to ipynbs in devtools, set `verbose: true` on the hook
2. staged one ipynb change for commit
3. committed, saw that only the changed ipynb was passed through `nbconvert`
4. `git reset HEAD^`
5. only stage the precommit hook
6. commit, see that we skip the `nb-output-clear` step
```[tasklist]
```
=> Speed up nb-output-clear step in pre-commit

src/pudl/metadata/classes.py, src/pudl/metadata/resources/eiaaeo.py
doesn't really close #3581, but sure helps!
Table 54 has a bunch of confusingly heterogeneous data, here I'm sorting them and organizing them in some way.
Also, I'm introducing a new pattern of defining schemas in a 'staging area' that can be reviewed + checked in, but don't get published or expect there to be an asset involved. This enables the following flow:
1. figure out some resource designs ahead of time - often we'll want to design multiple resources at once due to interdependencies
2. merge that
3. work on new assets that generate those resources, maybe even in parallel!
4. promote and merge new assets as they become complete, so we don't have to wait for *all* assets to be done to use *any* assets
Nothing seems to …
=> Enumerate all AEO table 54 schemas.

docker/gcp_pudl_etl.sh
Fix quoting in the nightly build script which is attempting to copy all hourly parquet outputs into the distribution directory.
Closes #3601
Unfortunately testing this part of the nightly build script is annoying, so I haven't tested it.
=> Fix quoting in hourly parquet deployment command

src/pudl/extract/eia176.py, src/pudl/extract/eia191.py, src/pudl/extract/eia757a.py, src/pudl/extract/eia860m.py, src/pudl/extract/eia861.py, src/pudl/extract/eia923.py, src/pudl/extract/extractor.py, src/pudl/extract/nrelatb.py, src/pudl/extract/phmsagas.py
When debugging the 2024-04-27 nightly build failure #3593 I noticed that there were a bunch of asset definitions annotated with required resource keys that were not being used. My guess is that this was due to cut-and-paste without understanding how Dagster resources work, but maybe I'm the one misunderstanding them?  If you don't actually use a resource within the asset being defined, are there good reasons to nevertheless supply it with these resources?
```[tasklist]
```
=> Remove unused resource keys from asset definitions

docs/release_notes.rst, src/pudl/workspace/datastore.py
* Update to use May, 2024 archives for the EIA Bulk Electricity data (used to fill in missing fuel prices in the EIA-923 fuel receipts and costs table).
* This data contains prices through February, 2024 (3 more months than the previous archive, which ran through November, 2023)
* Materialized the `core_eia__yearly_fuel_receipts_costs_aggs` assets locally and verified that they include new months of data, compared to the most recent nightly build outputs.
```[tasklist]
```
=> Update EIA Bulk Electricity archive/DOI.

src/pudl/etl/__init__.py, src/pudl/metadata/resources/eiaaeo.py
Fix a tiny units inconsistency I saw when reviewing the EIA AEO table documentation.
```[tasklist]
```
=> Update EIA AEO table description units to be consistent with columns.

Makefile, test/validate/mcoe_test.py
We lost 9 rows in the annual capacity factor and MCOE outputs, which is almost certainly because we lost 9 rows in the annual `gen_eia923` outputs... which we already knew -- not sure why this didn't trip the validations up before and get included in the initial row count updates. 🤦🏼 
I also changed the `pytest-minmax-rows` make target to run on 8 CPUs instead of one to make doing this check faster and more convenient in the future. It used less than 10 GB of memory at peak, so this should not freeze anybody's computer up.
I ran `make pytest-minmax-rows` locally and they all passed.
=> Update expected MCOE row counts

.github/ISSUE_TEMPLATE/task.md
It's kind of annoying to keep typing the same sections over and over again when creating generic issues.
Added a template.
Copied the template text into an issue and hit the 'preview' tab.
=> Add template that includes overview/success criteria/tasks

docs/release_notes.rst
There's so much new data in the upcoming release that the release notes section for new data really needed to be broken down by data source. Otherwise it was an unreadable blob of text with different changes all mixed together.
I built the docs locally and they worked.
=> Organize the large new data section of release notes

test/validate/service_territory_test.py
Update row counts for the service territory tables, which now have additional utilities in them that were only found in the EIA-861 short form tables.
```[tasklist]
```
=> Update expected row counts in service territory tables.

docker/gcp_pudl_etl.sh
* Publish Parquet files to the public GCS & S3 buckets when the builds succeed.
* Create a `pudl_parquet.zip` archive containing all the Parquet outputs that we can point Kaggle at.
* Switch to using `zip` instead of `gzip` to compress SQLite files because Windows can only open `zip` archives and we don't want Windows users to have to download a 3rd party archive/compression utility.
Closes #3678
* Is there an easy way to give this a test besides doing a whole deployment?
```[tasklist]
```
=> Update nightly build script to quietly publish public Parquet outputs.

docs/data_access.rst, docs/index.rst
The nightly builds are passing and generating the new ZIP rather than gzip archives but... I forgot to update the links in the docs when I changed those file paths.
```[tasklist]
```
=> Update docs to link to .zip not .gz S3 archives

src/pudl/etl/__init__.py, src/pudl/etl/cli.py, test/conftest.py
Closes #3705 .
* we weren't running asset checks in our ETL when running in integration tests. Instead of making a new, different ETL job for integration tests, we now just run the same job we use everywhere else, but with whatever dataset configuration we have defined for the tests.
* we also weren't asserting that the ETL execution actually succeeded. Asset check failures currently cause `Exception`s, so we don't technically need this, but it seems prudent to assert success anyways.
* verified that the `fgd_equipment_null_check` asset check passes, by running the raw_eia860 assets and then the `_core_eia860__fgd_equipment` asset in Dagster
* ran integration tests with `make pytest-coverage` and saw the integration tests pass
* break the `fgd_equipment_null_check` by …
=> Make asset checks matter to integration tests

src/pudl/etl/cli.py, test/conftest.py
Closes #3708.
https://github.com/catalyst-cooperative/pudl/pull/3687 broke the `pudl_etl` command because `build_reconstructable_job` needs `pudl_etl_job_factory` to be in the same file: https://github.com/catalyst-cooperative/pudl/blob/c153929ea0090edd3d036b4db0fa15e4bcd003b1/src/pudl/etl/cli.py#L131-L139
This PR just reverts the `pudl_etl_job_factory` move that happened in https://github.com/catalyst-cooperative/pudl/pull/3687.
I also fleshed out [this issue](https://github.com/catalyst-cooperative/pudl/issues/3161) which would allow us to migrate away from the experimental and confusing `build_reconstructable_job` method.
- I ran `make pytest-coverage` and `pudl_etl` …
=> Move `pudl_etl_job_factory` back to `pudl.etl.cli.py`

docs/release_notes.rst, src/pudl/output/eia923.py
* Something appears to be wrong with the way we have been filling in gaps in fuel prices in the `out_eia923__fuel_receipts_costs` table using rolling averages. This was resulting in anomalously high fuel prices in some cases, identified first in deliveries of `BIT` to plants with `plant_id_eia` `8102` and `2832`.
* It's not clear whether the issue is resulting from the filling step, or the calculation of the rolling averages.
* If it's in the calculation of the rolling averages, then the `out_ferc1__yearly_steam_plants_sched402` table could also be affected, as the same routine is used there to calculate a smoothed estimate of ongoing capital additions.
* For now I have simply disabled the use of rolling averages to fill in the fuel prices until we can figure out exactly what's going on …
=> Disable rolling avg to fill missing fuel prices in EIA923 FRC table

src/pudl/validate.py
Changed the lower bound on the FERC Form 1 steam plants "not water limited ratio" validation test.
I ran the full data validations against a fresh database and they all passed.
=> Update allowable not water limited capacity ratio.

src/pudl/transform/ferc714.py
The builds failed last night with a FK violation from the new `core_ferc714__yearly_planning_area_demand_forecast` table, because it has 10 records for respondent ID 2, which doesn't show up in the respondent ID table. Half of those records contain only zeros, and the other half have values in only one column, so dropping all 10.
Materialized all FERC-714 tables locally and ran the FK checks and they passed.
```[tasklist]
```
=> Remove bad respondent ID 2

environments/conda-linux-64.lock.yml, environments/conda-lock.yml, environments/conda-osx-64.lock.yml, environments/conda-osx-arm64.lock.yml
=> Update conda lockfile for week of 2024-07-29

.github/ISSUE_TEMPLATE/quarterly_updates.md
Addresses a workflow failure that occurred with the `quarterly-update-issues` workflow: https://github.com/catalyst-cooperative/pudl/actions/runs/10212473537
Adds a title, which was missing.
I ran the workflow manually. See https://github.com/catalyst-cooperative/pudl/actions/runs/10255721513 and the corresponding issue #3764. The original workflow kicked off on the day/time expected, so no problem there.
```[tasklist]
```
=> Add title to quarterly updates issue template

terraform/main.tf
This PR updates our terraform config to include the mozilla development repo in our gcloud WIF pool.
* My understanding is that I just need this update to `main.tf`, then update the workflow file to use the workload identity pool with the appropriate service account. Is there anything else we need to do?
* When I run `terraform plan` there's a bunch of new superset resources that would be deleted because they haven't been migrated into terraform yet. Is there an easy/clean way to avoid that?
=> Add mozilla repo to wif pool

docs/dev/existing_data_updates.rst, docs/release_notes.rst, src/pudl/metadata/sources.py, src/pudl/package_data/settings/etl_fast.yml, src/pudl/workspace/datastore.py, test/integration/epacems_test.py
Closes #3762.
Adds Q2 of CEMS data into PUDL.
- Updated the Zenodo DOI for datastore.
- Updated docs to remove reference to non-existent asset groups
Generated the CEMS assets and all downstream outputs. Double checked to make sure that no validation tests are impacted, and ran minmax row tests.
```[tasklist]
```
=> Add Q2 2024 CEMS data

docs/release_notes.rst, src/pudl/workspace/datastore.py
Update Zenodo DOI for NREL ATB dataset to get their error corrections.
Closes #3777
* I re-ran the ETL for the NREL ATB assets locally.
* I checked whether there are any data validation tests for the ATB, and there aren't, so I didn't re-run the minmax rows.
```[tasklist]
```
=> Update DOI for NREL ATB to get error corrections

.github/workflows/release.yml
Our `release.yml` workflow doesn't currently trigger from PRs merging in for a fork.
- Updated `on` condition to include `pull_request`
- Updated conditional to correctly identify forks vs non-forked repos
=> Fix `release.yml` fork behaviors

docs/release_notes.rst
This PR closes out the release notes for our `v2024.8.0` release, as part of #3800 
I rebuilt the documentation locally and inspected the release notes page.
=> Close out v2024.8.0 release notes.

.github/workflows/pytest.yml
After merging #3823 I saw that the upload of coverage data to CodeCov was broken by some of the changes in that PR. This gets it back to working again.
I did some `workflow_dispatch` testing of the modified workflow with the integration & docs tests turned off, until I was able to get rid of the upload errors,and had the data showing up on CodeCov for the branch again with each push.
I've also told the CodeCov action to fail the check if the upload fails, so this kind of thing should get caught if it happens again.
=> Try to fix CodeCov report uploads in pytest workflow.

docker/Dockerfile
A new version of mamba came out, but I didn't catch it and failed to update the docker image when I was doing the other version updates so... yet another one-liner.
=> Bump mamba docker image version to 1.5.9

terraform/main.tf
- Mount the Cloud SQL `pudl-usage-metrics-db` to Superset cloud run instance
- Create a new bucket for raw usage metrics archives
- Give github action service account permission to write to the bucket
The usage metrics data can be viewed in superset and the github metrics are being saved to the new bucket.
```[tasklist]
```
=> Add pudl usage metrics gcp infrastructure

devtools/generate_batch_config.py
Increase the disk allocated to the nightly build machine from 80GB to 100GB since we're getting an error about running out of disk when we start zipping the output SQLite DBs.
Closes #3852 (hopefully)
Can't test this short of running the nightly builds.
```[tasklist]
```
=> Increase nightly build VM disk from 80GB to 100GB

src/pudl/package_data/glue/respondent_id_ferc714.csv, src/pudl/transform/ferc714.py
Closes #3839 and #3858
There were two main threads that needed pulling to get this table updates:
* **Table compatibility**: The csv table is static while the xbrl table is reported annually. A lot of the downstream analysis expects this table to be static. So the first step was to check whether or not the columns that we have in the CSV years had consistent data over the few XBRL years that we have. There were a small number of `eia_code`'s we needed to clean up, but besides that it was static. I then converted the XBRL data into a static table, then I concat-ed the tables and checked the static-ness again.
* **eia_code cleaning**: Not a ton but some cleaning necessary. Done all in `spot_fix_eia_codes` & `EIA_CODE_FIXES`
still todo …
=> FERC 714: Integrate the XBRL data Respondent ID table 

src/pudl/transform/ferc714.py
The 714 data got pushed (via #3842) and failed the nightly builds bc of this silly silly error:
```python
The above exception was caused by the following exception:
AssertionError: We found 1 duplicate errors, but expected 1 or less:
respondent_id_ferc714_csv  report_year  forecast_year  summer_peak_demand_forecast_mw  winter_peak_demand_forecast_mw  net_demand_forecast_mwh  respondent_id_ferc714
10801                        211         2013           2014                               0                               0                        0                    100
```
bc i had it as if len(baddies) >= 1 instead of if len(baddies) > 1.
(side personal note that I am continuously surprised that I've been doing this for this long but still regularly have to look up which one is > vs < and …
=> FERC 714: Fix defensive check

src/pudl/metadata/constants.py, src/pudl/metadata/sources.py
Closes #3886
Adds source metadata for `vceregen` so it's ready to be ingested by the archiver.
=> Add source metadata for `vceregen`

.pre-commit-config.yaml, docker/Dockerfile, environments/conda-linux-64.lock.yml, environments/conda-lock.yml, environments/conda-osx-64.lock.yml, environments/conda-osx-arm64.lock.yml
- Update to the micromamba v2 Docker image.
- Update to the newest version of the `hadolint-py` pre-commit hook since the old one started failing.
Note: [hadolint](https://github.com/hadolint/hadolint) seems to have been abandoned and [the prettier commit hook](https://github.com/pre-commit/mirrors-prettier) has been archived due to incompatible changes in the underlying prettier library, so we should probably try and replace those hooks (Dockerfile linting, and YAML linting/formatting)
- Ran a branch deployment using the new Dockerfile
```[tasklist]
```
=> Update to micromamba 2.0.2 Docker image.

.pre-commit-config.yaml, environments/conda-linux-64.lock.yml, environments/conda-lock.yml, environments/conda-osx-64.lock.yml, environments/conda-osx-arm64.lock.yml
=> Update conda lockfile for week of 2024-10-21

docs/templates/vcerare_child.rst.jinja
- Add a couple of extra links to the VCE data source docs for additional context. (ESIG paper + Kaggle notebook).
- Add a couple of additional errata about naming / FIPS codes.
Part of #3914
```[tasklist]
```
=> Add some links to the VCE RARE data source page.

docs/release_notes.rst, src/pudl/metadata/sources.py, src/pudl/workspace/datastore.py
Closes #3943.
Adds Q3 2024 CEMS data to the ETL.
- Updated the `working_partitions` to include the new quarter
- Updated the DOI
```[tasklist]
```
```[tasklist]
```
=> Add Q3 2024 CEMS data to ETL

docs/release_notes.rst, src/pudl/workspace/datastore.py
Closes #3944.
Add three more months of EIA bulk elec data (2024-06 through 2024-08)
- Update DOI
- Update release notes
```[tasklist]
```
```[tasklist]
```
=> EIA bulk elec q3 2024 integration

.github/ISSUE_TEMPLATE/versioned_release.md, CITATION.cff, docs/release_notes.rst
Wrap up the release notes for PUDL v2024.11.0 in preparation for release.
I rebuilt the docs locally and inspected them.
=> Close out PUDL v2024.11.0 release notes

.github/workflows/build-deploy-pudl.yml, .github/workflows/com-dev-notify.yml, .github/workflows/pytest.yml, docs/release_notes.rst, environments/conda-linux-64.lock.yml, environments/conda-lock.yml, environments/conda-osx-64.lock.yml, environments/conda-osx-arm64.lock.yml
=> Update conda lockfile for week of 2024-11-18

devtools/splink-ferc1-eia-match.ipynb, docs/release_notes.rst, src/pudl/analysis/plant_parts_eia.py
This PR updates the `devtools` notebook for FERC to EIA record linkage with `splink`. This notebook isn't actually run in production, but it's helpful for visualizing the model weights and the decisions that go into making the match. 
The notebook now runs with the latest version of `splink` and reads in parquet inputs from S3 instead of from dagster storage.
Updated the notebook to have more documentation cells and run with the latest version of splink. Also, fixed an error that was cropping up in the plant parts list creation with datetime types. I think this came up because I'm now reading in parquet inputs from S3 instead of dagster storage, and the `report_date` column was an object instead of a datetime.
```[tasklist]
``` …
=> Updates to splink FERC to EIA record linkage notebook

environments/conda-linux-64.lock.yml, environments/conda-lock.yml, environments/conda-osx-64.lock.yml, environments/conda-osx-arm64.lock.yml
=> Update conda lockfile for week of 2024-12-02

src/pudl/settings.py
The attribute docstrings for `pudl.settings` were listed as arguments. This PR moves the doc strings out of the class doc strings and below the attributes so they are rendered correctly in the docs.
```[tasklist]
```
```[tasklist]
```
=> Fix `pudl.settings` class doc strings

docs/data_access.rst, docs/templates/resource.rst.jinja
I added a parquet file download link to the data dictionary so it's easier for people to access the s3 files.
```[tasklist]
```
I built the docs locally and was able to download a parquet file.
```[tasklist]
```
=> Add parquet download link to data dictionary

src/pudl/transform/vcerare.py
This PR fixes the VCERARE row count `asset_check`. This check was using the expected row count for the full ETL, and would fail for the fast ETL. Now it handles both correctly.
=> Fix row count asset check for vcerare

src/pudl/transform/ferc714.py
Working on #3928
fixing asset check found in #3990
only check row nums for years that are in the dataset_settings
```[tasklist]
```
```[tasklist]
```
=> Fix FERC714 fast CI asset check

src/pudl/etl/__init__.py, src/pudl/etl/cli.py, src/pudl/transform/ferc714.py, test/conftest.py
Closes #3928 .
#3711 inadvertently disabled the asset checks again, in service of fixing `pudl_etl` 😞 
Getting rid of `pudl_etl` (#3161) seemed out of scope here, but I made the tests use the same `Definitions` as the nightly builds again.
Made the pandera checks all fail, ran `make integration-test`, and checked to make sure that the integration tests bailed out once we ran into a failure.
Then got other people to fix the failing asset checks and re-ran integration tests. They passed.
```[tasklist]
```
=> Make asset checks run in integration test

src/pudl/etl/cli.py, src/pudl/transform/vcerare.py, test/conftest.py
... the nightly builds are still broken because the reconstructable job doesn't want any parameters at all.
Moved the parameters to the wrapper function.
=> Make the reconstructable job not take any arguments at all.

src/pudl/metadata/classes.py
Addresses a lightweight version of https://github.com/catalyst-cooperative/pudl-archiver/issues/499 in concert with https://github.com/catalyst-cooperative/pudl-archiver/pull/506.
In the `pudl-archiver` repository, we want to make it possible to archive datasets that will never end up in the PUDL repository. Eventually, we'll want to fully separate these two repositories, which raises bigger questions about where the metadata should be defined, etc. But for now, we want to make it possible to add a dictionary of `NON_PUDL_SOURCES` to the `pudl-archiver` repository, to be called in a method similar to `from_pudl_metadata` in `frictionless.py`.
This method imports the `DataSource.from_id()` method from PUDL, which currently hardcodes `SOURCES` into the method. In order to make it possible …
=> Make it possible to pass another `sources` dict to DataSource

docs/release_notes.rst, src/pudl/metadata/classes.py
Relevant to https://github.com/catalyst-cooperative/pudl-archiver/pull/506.
In #4003 I updated `DataSource.dict_from_id()` to take `sources`. However, `from_id()` is an upstream method called in the `pudl-archiver` repository, and I neglected to add `sources` as a parameter here. This PR fixes this problem.
* Added `sources` as a parameter to `DataSource.from_id()`
* Made `SOURCES` the default in `from_id()` and not `dict_from_id()`. `from_id()` is more widely called both in PUDL and the `pudl-archiver` repo, and this removes duplicate defaults in the class.
```[tasklist]
```
```[tasklist]
```
=> Pass `sources` to `DataSource.from_id()`

src/pudl/analysis/pudl_models.py, src/pudl/metadata/classes.py
This PR fixes the nightly build failure caused by adding `sec10k` tables. This error occurred because I forgot to commit the database migrations with the new tables. However, after further consideration, I realized that including these `sec10k` tables in the SQLITE db there will be schema inconsistencies for outside contributors who can't pull the metadata from GCS. Because of this, this PR also updates the PUDL models assets to use only the parquet IO-manager.
=> Sec distribution fix

docs/release_notes.rst, src/pudl/workspace/datastore.py
Closes #4042 
- Add EIA bulk electricity data to PUDL
- Updated the DOI
- Updated the release notes
```[tasklist]
```
```[tasklist]
```
=> Update Q1 2025 EIA bulk electricity data

CITATION.cff, docs/data_sources/other_data.rst, docs/release_notes.rst
Close out the release notes for the v2025.2.0 release of PUDL.
- I moved a couple of the the "new data coverage" items up into "new data" because they were entirely new tables or datasets, rather than just extensions in time of existing datasets.
- Added some color to the EPA CAMD -- EIA crosswalk docs since we're doing more work there now.
Part of #4061 
```[tasklist]
```
- Ran the docs build locally and it passed.
```[tasklist]
```
=> Close out release notes for PUDL v2025.2.0

devtools/zenodo/zenodo_data_release.py, docker/gcp_pudl_etl.sh, docs/release_notes.rst, src/pudl/metadata/classes.py, test/unit/metadata_test.py
Closes #4069 .
I wanted to output a datapackage descriptor for the PUDL viewer to use as the basis for search. Up until now it's been using a vendored version of the Datasette `metadata.yaml` that we generate.
We *could* achieve the effect of "have an up-to-date metadata for PUDL viewer" just by *not* cleaning up the metadata.yaml out of the nightly builds, but distributing some wacky bespoke metadata format seems silly. So I made the necessary changes to output a proper `datapackage.json`.
* added `to_frictionless` methods to `Package` and `Resource` so we can use their "to a valid datapackage.json" functionality
* added a function to the `gcp_pudl_etl.sh` script to write this datapackage out.
```[tasklist]
```
Kicking off a …
=> feat: output a datapackage.json for PUDL parquet files.

terraform/.terraform.lock.hcl, terraform/main.tf
Part of catalyst-cooperative/parquet-fe-prototype#21.
Adds a log sink for PUDL viewer logs to be persisted.
* ran `terraform fmt` to make sure our file stays clean - only look at [*this commit*](https://github.com/catalyst-cooperative/pudl/pull/4071/commits/a076df9443de9023454b3230121da27a38a1f1a8) and later ones if you want to skip those changes
* added a bucket, a log sink, and some permissions to allow the log sink to write to the bucket
```[tasklist]
```
Looked in the console after terraform apply and there does appear to be a log sink and corresponding bucket. Hopefully I'll check in the morning and see some logs in that bucket.
```[tasklist]
```
=> Add PUDL viewer log sink

README.rst, docs/data_access.rst, docs/data_dictionaries/index.rst, docs/index.rst
As part of launching the PUDL viewer we should actually include it in our docs.
```[tasklist]
```
Built docs locally and looked at them.
```[tasklist]
```
=> chore: add PUDL viewer to docs

.github/ISSUE_TEMPLATE/nightly_build_failure.md, .github/ISSUE_TEMPLATE/quarterly_updates.md, .github/ISSUE_TEMPLATE/task.md, .github/ISSUE_TEMPLATE/versioned_release.md, .github/pull_request_template.md
https://github.blog/changelog/2025-02-18-github-issues-projects-february-18th-update/#tasklist-blocks-will-be-retired-and-replaced-with-sub-issues
Converted tasklists to just normal lists.
=> chore: remove tasklists since they're being replaced.

devtools/datasette/fly/production.toml, devtools/datasette/fly/staging.toml
Nightly builds keep failing datasette step with a timeout. The app eventually starts up but only after the timeout is triggered. 
15 minutes -> 25 minutes.
Don't think there's anything to change here.
Just looked in the documentation for a cap on the wait timeout and couldn't find one.
I could have downloaded the nightly build full outputs from GCS and run the publish command, but that requires a bunch of disk space cleanup and that seemed like a distraction, whereas the risk of 'push-and-wait' seems pretty low.
=> fix: up fly app timeout

dbt/models/ferc1/core_ferc1__yearly_hydroelectric_plants_sched406/schema.yml, dbt/models/ferc1/core_ferc1__yearly_pumped_storage_plants_sched408/schema.yml, src/pudl/validate.py, test/validate/bf_eia923_test.py, test/validate/eia_test.py, test/validate/fbp_ferc1_test.py, test/validate/ferc1_test.py, test/validate/frc_eia923_test.py, test/validate/fuel_ferc1_test.py, test/validate/gens_eia860_test.py, test/validate/gf_eia923_test.py, test/validate/mcoe_test.py, test/validate/notebooks/validate_bf_eia923.ipynb, test/validate/notebooks/validate_fbp_ferc1.ipynb, test/validate/notebooks/validate_frc_eia923.ipynb, test/validate/notebooks/validate_fuel_ferc1.ipynb, test/validate/notebooks/validate_gens_eia860.ipynb, test/validate/notebooks/validate_gf_eia923.ipynb, test/validate/notebooks/validate_mcoe.ipynb, test/validate/notebooks/validate_plants_steam_ferc1.ipynb, test/validate/plants_steam_ferc1_test.py
This PR removes a number of data validations that we're deprecating or that are duplicative, including:
- `check_unique_rows`
- `vs_self` (a statistical distribution check)
- `vs_historical` (another statistical distribution check)
Closes #4182
* I removed the functions implementing these checks from `pudl/validate.py`
* Removed all tests from under `test/validate` that relied on these functions.
* Updated all of the weighted quantile notebooks not to use `vs_self` or `vs_historical` (deleted related cells)
* For `check_unique_rows` I verified that every test was checking the set of columns that already defined the primary key for the table it was running on.  In 2 instances, this wasn't the case, but the columns being checked were an ad-hoc combination including plant `capacity_mw` in …
=> Remove obsolete vs_self, vs_historical, & check_unique_rows tests

terraform/pudl-viewer.tf
We renamed `parquet-fe-prototype` to `eel-hole` so we need to update the db migration job.
Ran `terraform plan` to see if the job would try to use `eel_hole` instead of `parquet_fe_prototype`.
Confirmed that that command works in docker compose:
```
$ docker compose exec eel_hole bash
<snip>
```
=> fix: keep db migration job working with rename of parquet-fe-prototype

devtools/zenodo/zenodo_data_release.py
Closes #4184 .
It *looks* like we can catch this exception by catching OSError, too. But reproducing this EINT locally is tricky so this is a bit of a guess.
* add catch on OSError in addition to RequestException
* use `stream=True` to use multipart uploading built in to requests - hopefully that behaves a little more stably.
* didn't add multipart resume - it seemed complicated / not worth it
* downloaded the .zip files from the aws nightly builds to `$PUDL_NIGHTLY`
* ```
./zenodo_data_release.py --publish --env "sandbox" --source-dir "$PUDL_NIGHTLY" --ignore $PUDL_NIGHTLY/pudl_parquet_datapackage.json --ignore $PUDL_NIGHTLY/parquet/
```
The EINT also seems to have stopped happening in the most recent nightly builds so …
=> fix: retry on OS errors

environments/conda-linux-64.lock.yml, environments/conda-lock.yml, environments/conda-osx-64.lock.yml, environments/conda-osx-arm64.lock.yml
=> Update conda lockfile for week of 2025-04-14

src/pudl/scripts/dbt_helper.py
Pre-cleanup before making the changes for #4175 in order to make those easier to make (and review).
The dbt helper has some confusing naming conventions that make it harder to add functionality. To separate out the work of adding functionality and cleaning up the code, I am first doing a no-op refactor, meaning the functionality should be unchanged.
Renamed some functions and broke out functionality, in particular:
- `AddTableResult` renamed to `UpdateResult` since it is a generic status message for an update
- Refactored `generate_row_counts` into functions that get the existing row counts, compute the new ones, combine the old with the new, and write the results to csv, since generate row counts suggests only that row counts are computed, not that they are also written to file
- Added …
=> Refactor dbt helper

docs/conf.py
Removes the banner announcing our 2025 annual user survey from the top of our docs.
=> Remove PUDL user survey banner from documentation.

docker/gcp_pudl_etl.sh, test/integration/dbt_test.py
We have an integration test for the `dbt_helper` script which gets run in the nightly builds, but it had the `etl-fast` target hard-coded, so it was incorrectly updating row counts based on the Full ETL outputs, causing the nighty tag update to fail.
- This PR updates it to use whatever the correct dbt target is, based on the ETL settings file (full vs. fast) as we do for the other dbt tests.
- In the course of debugging this I also saw that we were echoing the PUDL Bot's PAT to our logs, so I changed the build script to avoid doing that.
- I revoked the old PAT and created a new one.
- There were also still some SEC 10-K tables being excluded from the integration tests, which is no longer appropriate, since those tables are now brought in using Zenodo just like everything else.
Closes …
=> Use correct target in dbt_helper integration test

test/validate/mcoe_test.py
For some reason the MCOE null columns check for fuel_cost is crashing the pytest worker in the nightly builds, even though it passes locally. Skip that validation for the moment to prevent this from blocking quarterly updates / nightly builds.
=> Skip MCOE null cols check that is crashing pytest worker.

src/pudl/analysis/spatial.py
This small PR resolves the GeoPandas deprecation warnings:
```python
/home/runner/work/pudl/pudl/src/pudl/analysis/spatial.py:147: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
````
Make sure to update relevant aspects of the documentation:
Run tests
=> Resolve GeoPandas library warnings

.pre-commit-config.yaml, environments/conda-linux-64.lock.yml, environments/conda-lock.yml, environments/conda-osx-64.lock.yml, environments/conda-osx-arm64.lock.yml, test/integration/dbt_test.py
=> Update conda lockfile for week of 2025-05-11

dbt/README.md, dbt/dbt_project.yml, dbt/profiles.yml, dbt/tests/data_tests/generic_tests/check_row_counts_per_partition.sql
- To ensure that we get our `v2025.5.0` data release out on time, this PR short-circuits the row count checks in our Fast ETL outputs, as there's some work required to make sure they behave consistently in local and CI environments, and that's creating friction in the development process right now.
- It also removes the `nightly` target for dbt, since that was primarily useful in the context of our initial migration of the validation tests, which is now complete.
I ran the dbt tests locally with both `etl-full` and `etl-fast` targets, with full ETL outputs in my `PUDL_OUTPUT` directory, and the fast tests did not complain about row count violations, while the full tests did (I have some leftover FERC-714 tables that are from another PR).
=> Disable row counts for etl-fast and remove nightly dbt target

src/pudl/helpers.py
Uses a `multiprocessing` option that lets us pre-import a bunch of modules into a 'fork server'. Then all the child processes don't have to re-import e.g. PUDL and sklearn and all that - saves us a few seconds per task, which is nice when so many of our tasks take longer to spin up than to run.
I made this change while trying to work on #4132  - figured I should get this into `main` as a separate small PR instead of tying it to an unrelated, more gnarly piece of work.
Make sure to update relevant aspects of the documentation:
* ran the fast ETL locally using dagster UI and nothing blew up
=> feat: use forkserver when available for speed

dbt/package-lock.yml, dbt/seeds/etl_full_row_counts.csv, devtools/generate_batch_config.py
Nightly builds are currently failing due to concurrency issues resulting from all the new time series imputations and larger data with the quarterly update. This PR temporarily increases the resources available to the nightly builds so we can get the quarterly release out on time, while we figure out a better concurrency management setup.
- Also add a couple of missing row-count expectations from the EIA-860/923 updates.
- Update package versions in dbt environment.
=> Bloat the Google Batch VM

docker/gcp_pudl_etl.sh
We haven't been able to successfully redeploy Datasette to Fly.io since March 28th (6 weeks...) which feels like a functional deprecation, even though we haven't gotten the new user portal to feature parity yet.
The nightly builds currently spend ~45 minutes attempting to redeploy Datasette whenever they run, to no effect.
This PR comments out the Datasette deployment actions in the nightly build script, so that we can stop making those pointless attempts, unless / until we actually go in and fix whatever the problem is. Or, maybe more likely, until we get the PUDL Portal to feature parity and start deploying it to https://data.catalyst.coop, usurping Datasette completely.
Should update our data access documentation and various other links to remove this access mode?  I'm assuming that …
=> Disable Datasette deployment in nightly builds

.github/ISSUE_TEMPLATE/versioned_release.md, docker/gcp_pudl_etl.sh
- Update data release issue template
- Use correct filename when removing `pudl_dbt_tests.duckdb` in nightly build script so we don't distribute it.
Closes #4278
=> Post PUDL v2025.5.0 release cleanup.

dbt/models/ferc1/out_ferc1__yearly_all_plants/schema.yml, dbt/models/ferc1/out_ferc1__yearly_hydroelectric_plants_sched406/schema.yml, dbt/models/ferc1/out_ferc1__yearly_pumped_storage_plants_sched408/schema.yml, dbt/models/ferc1/out_ferc1__yearly_small_plants_sched410/schema.yml, dbt/models/ferc1/out_ferc1__yearly_steam_plants_fuel_sched402/schema.yml, dbt/models/ferc1/out_ferc1__yearly_steam_plants_sched402/schema.yml, docs/templates/ferc1_child.rst.jinja, test/integration/ferc_xbrl_extract_test.py, test/validate/ferc1_test.py
- Removed some leftover infrastructure in the FERC 1 validation tests that was needed to check for unique record_id values in a number of columns -- these tests had already been migrated into dbt.
- Added some missing unique `record_id` checks in FERC 1 output tables.
- Moved the FERC 1 XBRL filter for freshest data test from validtion to integration tests... since it should work on both full and fast FERC XBRL derived SQLite DBs.
Closes #4283
Closes #4282
=> Remove and/or relocate some FERC Form 1 data tests

.pre-commit-config.yaml
We're supposed to use `ruff-check` instead of `ruff` now, I guess. Also, dropping the `--exit-non-zero-on-fix` didn't seem to change the behavior when there was a linting error that got auto-fixed. So we might as well remove it.
I added an extra newline to the import block of `transform/eia930.py` then tried to commit it. `ruff` complained and the commit didn't go through. I had to manually add the fix from `ruff` before re-committing.
=> chore: fix 'legacy alias' for ruff pre-commit check

src/pudl/analysis/timeseries_cleaning.py, src/pudl/metadata/dfs.py
This PR adds a new imputation flag, `BAD_YEAR`. This flag indicates that an entire year of data was dropped for a specific respondent because there was too much missing data. This should ensure that anytime the `imputed` column isn't equal to the `reported` column, there will be a corresponding `flag` for the value.
=> Add extra flag to timeseries imputation for bad years of data

dbt/seeds/etl_full_row_counts.csv, docker/gcp_pudl_etl.sh, docs/dev/testing.rst
Copy the observed full ETL row counts to the nightly build outputs so they can be generated and used without needing to to run the Full ETL locally.
=> Test saving observed dbt row counts in nightly builds

dbt/README.md, src/pudl/dbt_wrapper.py, src/pudl/scripts/dbt_helper.py, test/integration/dbt_test.py, test/unit/dbt_wrapper_test.py
Closes #4132 . For real this time.
We work on dagster assets but have to run validation tests with dbt nodes. dbt has no idea what the dependencies in dagster are so it's hard to select "all downstream assets" or somesuch. Plus the dbt names are much longer.
* add a flag to dbt_helper validate to pass in dagster selections instead
* add stub translation logic to `dbt_wrapper.py`
* add stub unit tests
Make sure to update relevant aspects of the documentation:
file structure:
```
your_dbt_project/
├── dbt_project.yml            # Required: Project configuration
├── models/                    # Required: Directory for models (can be empty)
└── models/sources.yml         # Defines your sources
```
source should only include …
=> feat: translate dagster asset selections to dbt node selections

.github/workflows/pytest.yml
**should** run integration tests, they should fail, and coverage should fail also.
but, didn't make any changes to make that happen. just outputting some debug logs.
=> debug: log out components of run_code_checks

.github/workflows/pytest.yml
In #4429 we found that if `change_filter` itself fails, the downstream `ci-integration` and `ci-coverage` jobs are marked as `skipped`, which [allows the merge to continue](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/about-protected-branches#require-status-checks-before-merging).
because we were setting the `run_code_checks` output to a value that included `github.event.merge_group` - which is either `null` (not in merge queue) or an `Object` (while in merge queue). This then got rendered as a mapping within pytest.yaml, instead of a boolean, which caused the [`change_filter` job to fail](https://github.com/catalyst-cooperative/pudl/actions/runs/16331365834).
See #4444 for a PR where I set up:
- a `fake-main` …
=> fix: force `run_code_checks` to be a valid boolean value

test/unit/dbt_helper_test.py
Closes #XXXX.
It was hard to test the whole flow of row count updates - "I have this asset table, this old rowcounts csv, this schema, and I expect *this* new rowcounts CSV".
Added a test that does that + allows for more parametrization.
ran the dang tests
=> Test calculate rowcounts

.github/workflows/pytest.yml, CITATION.cff, docs/release_notes.rst
- Update release metadata & notes for the PUDl v2025.8.0 release.
- Exclude files that get edited during release notes close-out from triggering integration tests in CI (won't help this time b/c changing them means editing `pytest.yml` which itself will trigger the integration tests, but it'll be nice for next time)
(Partially) closes #4542 
- I  built the docs locally and reviewed the new release notes page.
=> Close out release notes for PUDL v2025.8.0

docs/dev/data_validation_quickstart.rst, docs/dev/data_validation_reference.rst, src/pudl/dbt_wrapper.py, src/pudl/scripts/dbt_helper.py, test/unit/dbt_helper_test.py
Closes #4126 .
* Initial draft for debugging data validation failures.
Make sure to update relevant aspects of the documentation:
=> dbt docs: debugging failures

terraform/pudl-viewer.tf
Fixes the permissions error found in [this attempt at loading the PUDL viewer logs](https://github.com/catalyst-cooperative/pudl-usage-metrics/actions/runs/17542986952/job/49818068262).
Added the missing permissions block in terraform.
Got this from `terraform plan`:
```
+ resource "google_storage_bucket_iam_member" "usage_metrics_etl_pudl_viewer" {
+ bucket = "pudl-viewer-logs.catalyst.coop"
+ etag   = (known after apply)
+ id     = (known after apply)
+ member = "serviceAccount:pudl-usage-metrics-etl@catalyst-cooperative-pudl.iam.gserviceaccount.com"
+ role   = "roles/storage.legacyBucketReader"
}
+ resource "google_storage_bucket_iam_member" "usage_metrics_etl_pudl_viewer" {
+ bucket = "pudl-viewer-logs.catalyst.coop"
+ etag   = (known after apply)
+ id     = (known after apply)
+ …
```
=> fix: allow usage metrics ETL to access viewer logs
