catalyst-cooperative/pudl

- pudl/constants.py
- pudl/datastore.py
- pudl/extract/epacems.py
- pudl/init.py
- pudl/models/epacems.py
- pudl/settings.py
- pudl/transform/epacems.py
- scripts/init_pudl.py
- Currently the download is *very slow*, probably for FTP reasons.
More CEMS stuff on the way!
> Add EPA CEMS hourly

- .travis.yml
- ci/install_travis.sh
- ci/setup_postgres.sh
- environment.yml
- setup.cfg
- Minor edits to `environment.yml`
- `matplotlib` is used in analysis.py
- `dbfread` is in conda now
- The py.test markers in `setup.cfg` need some thought
- Progress toward #147
> Add Travis files, borrowing heavily from pandas

- docs/getting_started_for_linux.md
- docs/getting_started_mac.md
- docs/getting_started_pc.md
- Point to `environment.yml`
- Note that CEMS is large, slow, and not automatically loaded
> Install docs updates

- pudl/init.py
> Add a more informative error when drop_tables fails

- pudl/models/epacems.py
Previously I thought it was faster, but it's not. (At least with [WAL settings turned down](https://github.com/catalyst-cooperative/pudl/issues/171#issuecomment-435687908).)
Here's my test for two states. The "finalizing" includes the `ALTER TABLE SET LOGGED`.
Unlogged:
```
Loading    EPA CEMS took 00:05:04
Finalizing EPA CEMS took 00:01:30
```
Logged:
```
Loading    EPA CEMS took 00:05:02
Finalizing EPA CEMS took 00:02:41
```
> Stop using UNLOGGED then ALTER TABLE SET LOGGED for CEMS

- README.rst
I was curious about the project and ran into this broken link while reading the README.
> Fix broken README link

- src/pudl/convert/epacems_to_parquet.py
- Be explicit about types, and convert them as the CSV is read in.
- Partition on original CEMS data year (as the datapackages do) instead of UTC year.
- Now works for zero-row data and state-years with all-missing measurement code variables.
Fixes #451.
> Adjust type conversion in epacems_to_parquet

- devtools/harvesting_debug.ipynb
- src/pudl/analysis/mcoe.py
- src/pudl/helpers.py
- src/pudl/output/eia860.py
- test/validate/mcoe_test.py
The monthly fuel_cost should be the same size as months hr_by_gen. 
Slight investigation into Issue #608. Added some extra in-line comments, 
but did not implement a fix.
Also! I changed the de-normalization of the entity tables in the 
generators_eia860 output table. We should have done this a while ago.
All the data validation tests are now passing. Close Issue #752.
> Validate new dois

- .github/workflows/build-docker-image.yml
Turns out that `dockerfile` should be used instead of `file`.
> Bump build-push-action to @v2 and fix arguments.

- devtools/datasette/metadata.yml
- devtools/datasette/publish.sh
This is a basic set of metadata for running a ferc1 + pudl Datasette instance either locally or remotely. And also a little shell script that will deploy to Cloud Run if you've got authentication for the Catalyst Coop PUDL project on The Googs
> Add basic Datasette metadata and deployment script

- src/pudl/output/pudltabl.py
- src/pudl/package_data/notebooks/how_to_access_pudl.ipynb
- src/pudl/package_data/notebooks/how_to_use_pudl_out.ipynb
> add output and access notebooks

- .github/ISSUE_TEMPLATE/epic.md
I created an epic template using github's legacy issue template method. Admins can create issue templates with more features in the [repo's settings tab](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository).
Template [google doc](https://docs.google.com/document/d/1snL7AXNyZPATe5gQ5PkFzF2g3q0CNlm88W3NfS7R0hU/edit#).
> Epic template. 

- src/pudl/transform/ferc1.py
I think what made this slightly trickier to debug was that the `df` in question had a multiindex on both rows and columns. This made the simple swap suggested by the deprecation warning, `df.groupby(level=1).sum()`, ambiguous and fail.
This function is quite old and could be simplified with a refactor, but I stuck to the original scope and only fixed the API deprecation. I did that by `.stack`-ing away the column multiindex, then using `.groupby(level=<original_index>).sum()`
This closes #1173
> fix pandas API deprecation (issue #1173)

- src/pudl/helpers.py
require the county and state be available before getting the fips code
> Bb fips fix

- docs/data_access.rst
- docs/dev/clone_ferc1.rst
- docs/dev/data_guidelines.rst
- docs/intro.rst
> Remove lingering data package refs in docs

- .readthedocs.yaml
- src/pudl/output/epacems.py
- test/integration/epacems_test.py
- test/unit/output/epacems_test.py
- tox.ini
Man it's amazing how reliably not testing something means it has bugs in it.
> Bring in year_state_filter tests & improvements from pudl_catalog

- .mypy.ini
- devtools/environment.yml
- src/pudl/etl.py
- src/pudl/output/epacems.py
- test/integration/epacems_test.py
Also bumped the max version of `recordlinkage` to 0.15
Minor formatting changes.
> Use partial function in map of EPA CEMS ETL

- docs/release_notes.rst
- src/pudl/etl.py
- src/pudl/extract/eia861.py
- src/pudl/metadata/codes.py
- src/pudl/metadata/resources/eia.py
- src/pudl/transform/eia860.py
> Clean operational_status_code using metadata encoder

- src/pudl/output/ferc1.py
Covers issue #1619
add `opex_nonfuel` column to add ferc1 plant tables in the output later so the all_plants_ferc1() table has complete O&M Cost data from all tables in one place.
> add opex_nonfuel column to all FERC1 plant tables in output layer for all_plants_ferc1 table

- .github/workflows/pre-commit-ci-auto-merge.yaml
- .github/workflows/tox-pytest.yml
Automatically merge dependabot and pre-commit-ci PRs if they pass all checks.
> Dependabot auto merge

- .github/workflows/build-deploy-pudl.yml
Add workflow_dispatch support to nightly builds workflow so we can manually trigger builds if we want.
> Add workflow_dispatch support to nightly builds

- src/pudl/workspace/datastore.py
- src/pudl/workspace/resource_cache.py
I also gave the role Service Usage Consumer to the members@catalyst.coop group so we can all use the GCS cache.
> Add gcs and bypass cache args to datastore cli

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/epic.md
- .github/ISSUE_TEMPLATE/feature_request.md
Remove the very old reference to Postgres and add some more detailed questions.
> Update bug report issue template

- docs/dev/nightly_data_builds.rst
Updated the docs to include nightly build failure etiquette.
following:
> Updated docs to include nightly build failure etiquette.

- src/pudl/analysis/allocate_net_gen.py
Addressing #2049 from @arengel & @jrea-rmi
> remove pesky rounds on floats

- docs/release_notes.rst
Plz read! I tried to include all of the big PRs but not every single one of the PR's that went into #1665
> add release notes for xbrl integration

- src/pudl/analysis/service_territory.py
- src/pudl/analysis/state_demand.py
- src/pudl/cli.py
- src/pudl/convert/censusdp1tract_to_sqlite.py
- src/pudl/convert/datasette_metadata_to_yml.py
- src/pudl/convert/epacems_to_parquet.py
- src/pudl/convert/ferc_to_sqlite.py
- src/pudl/convert/metadata_to_rst.py
- src/pudl/package_data/settings/etl_full.yml
- src/pudl/workspace/datastore.py
- src/pudl/workspace/setup_cli.py
We've lost the ability to change the log level for most CLI commands because the loglevel args aren't being passed into the `pudl.logging_helpers.configure_root_logger()` calls. Also, not all commands provide logfile and loglevel arguments. 
This PR adds loglevel and logfile CLI args to all PUDL commands and passes them to the `pudl.logging_helpers.configure_root_logger()` function calls. 
following:
for details on how to run the full test suite locally if …
> Add loglevel and logfile to all CLI commands

- devtools/datasette/publish.sh
- docs/release_notes.rst
- src/pudl/metadata/classes.py
- src/pudl/metadata/sources.py
- src/pudl/metadata/templates/datasette-metadata.yml.jinja
- src/pudl/settings.py
- test/integration/datasette_metadata_test.py
> Add FERC XBRL DBs to datasette deployment.

- pyproject.toml
- setup.py
This includes only a bugfix from @grgmiller in the subplant unit identification process for EPA CEMS.
> v2022.11.30

- .github/workflows/build-deploy-pudl.yml
- docker/gcp_pudl_etl.sh
- docs/dev/nightly_data_builds.rst
- setup.py
This PR adds support for copying nightly build outputs to our new `s3://intake.catalyst.coop` bucket. 
See the catalyst-cooperative/pudl-catalog#70 PR for the supporting changes in the `pudl-catalog` repo.
following:
for details on how to run the full test suite locally if you need to debug a
particular failure.
descriptive enough for developers and users to understand your code.
[data validation tests](https://catalystcoop-pudl.readthedocs.io/en/latest/dev/te …
> Add AWS creds to build-deploy-pudl action and copy outputs to s3 bucket

- src/pudl/metadata/classes.py
Currently the documentation build *always* pulls metadata from Zenodo, which is flaky. See #2149.
This PR provides default `local_cache_path` and `gcs_cache_path` values so that when there's local data, or the build environment has GCS credentials (e.g. in our CI / github actions) the metadata can be obtained from those more reliable sources. I *think* that when neither of those are available (e.g. in the ReadTheDocs build) it will gracefully fall back on Zenodo, but this PR is partly to test that.
Right now the default local and GCS paths are hard coded deep inside the `DataSource` class, which is not ideal.
following:
times over …
> Mitigate zenodo dependency in docs build

- setup.py
Update to the most recent version (v0.8.0) of the [FERC XBRL Extractor](https://github.com/catalyst-cooperative/ferc-xbrl-extractor/tree/v0.8.0)
following:
for details on how to run the full test suite locally if you need to debug a
particular failure.
> Update to new version of FERC XBRL Extractor

- docker/Dockerfile
- docker/docker-compose.yml
- setup.py
- test/test-environment.yml
I added awscli v1 to `install_requires` which ended up creating dependency issues in other repositories that depend on pudl. I used v1 because v2 is not available [on conda forge](https://github.com/aws/aws-cli/issues/4947). The AWS cli is only needed for the nightly builds to copy the outputs to s3 so I removed awscli v1 from the package and now awscli v2 is installed directly in the docker image. 
This PR also relaxes the `google-cloud-sdk` version so it can stay more up-to-date. 
following:
[Running Tests with Tox](https://catalystcoop-pudl.readthedocs.io/en/latest/dev/te …
> Move awscli from pudl package to docker image

- src/pudl/metadata/fields.py
- test/validate/ferc1_test.py
* Replace lingering references to `transmission_ferc1` with `transmission_statistics_ferc1`
> Replace lingering transmission_ferc1 w/ transmission_statistics_ferc1

- docs/dev/annual_updates.rst
- docs/dev/datastore.rst
- docs/intro.rst
- docs/release_notes.rst
Exactly what it says on the tin.
One hiccup - I'm not completely sure if the changes in `Annual Updates` are strictly correct - @zschira maybe you have better insight?
> Update documentation to refer to `archiver` and not `scrapers` or `zenodo-storage`

- .github/workflows/com-dev-notify.yml
Notifies the community-dev slack channel when a user outside of the catalyst-cooperative github org creates an issue or discussion.
This action will only work once the workflow file is on main.
> Notify community-dev channel

- docs/CONTRIBUTING.rst
As discussed in the community development meeting, I added a few simple points about how we do technical design. I added a couple things pointing people to Discussions also.
> Add design process documentation

- docs/release_notes.rst
We forgot to add release notes about the *substantial* work that went into allocation fuel consumption, so here the are belatedly.
- ~Make sure you've included good docstrings.~
- ~For major data coverage & analysis changes, [run data validation tests](https://catalystcoop-pudl.readthedocs.io/en/latest/dev/testing.html#data-validation)~
- ~Include unit tests for new functions and classes.~
- ~Defensive data quality/sanity checks in analyses & data processing functions.~
> Add fuel allocation release notes

- docs/release_notes.rst
This is just the release notes for #2224
> Ferc to EIA match release notes

- devtools/materialize_asset.py
- src/pudl/io_managers.py
- src/pudl/output/ferc1.py
- test/conftest.py
Relates to #2318 and #2294 - this is the primary key duplication fix mentioned.
Branched off of `dagster_xbrl_test_fix` so the xbrl stuff would be in.
But I think we should probably merge #2318 into `dagster-asset-etl` and then #2321 into `dagster-asset-etl`, and then we can merge this change into `dagster-asset-etl` as well.
When running the unit tests, I still get a ForeignKeyError, though:
```
=================================== FAILURES ===================================
________ [doctest] pudl.io_managers.SQLiteIOManager.check_foreign_keys _________
205
206         Examples:
207         This method can be used in the test suite or a jupyter notebook for debugging.
208
209             >>> from pudl.io_managers import pudl_sqlite_io_manager
210             >>> from dagster import …
```
> Fix primary key duplication

- setup.py
In the spirit of keeping `main` up to date with `dev` when nightly builds pass, here is a tiny PR.
> Merge dev into main

- setup.py
Merges changes from #2351 into dev.
> Merge s3 readme url changes into `dev`

- docker/gcp_pudl_etl.sh
- docker/local_pudl_etl.sh
- src/pudl/cli.py
- src/pudl/convert/epacems_to_parquet.py
- src/pudl/etl/epacems_assets.py
- src/pudl/etl/output_assets.py
- src/pudl/io_managers.py
- src/pudl/package_data/settings/etl_fast.yml
- src/pudl/settings.py
- test/conftest.py
- test/integration/epacems_test.py
> Consolidate EPA CEMS parquet files

- src/pudl/etl/__init__.py
- src/pudl/io_managers.py
- test/unit/io_managers_test.py
@zaneselvans flagged in #2403 we aren't raising an error when an asset using the pudl_sqlite_io_manager does have a corresponding table schema defined in `pudl.metadata.resources`. This PR throws and error in this case and adds some additional SQLiteIOManager tests.
> Throw error when db is missing table schema

- src/pudl/io_managers.py
Prior to the 861 and 714 dagster integration, the SQLite database never became locked because none of the `df.to_sql()` calls took longer than 5 seconds, the default timeout before a DB locked exception is thrown. 714 and 861 introduced 1) larger tables that take longer to load to the db and 2) more tables that are being written to the database which increases the number of processes waiting to write to the db.
Luckily, we can adjust [the timeout value](https://docs.python.org/3/library/sqlite3.html#sqlite3.connect)! I set the default to 1000 seconds because 714 takes about 800 seconds on my computer. I think we could probably lower this timeout value because I think each chunk of a pandas dataframe gets its own connection though I'm not sure.
We could also add a retry to the …
> Add sqlite timeout

- docs/dev/run_the_etl.rst
This PR adds a warning in the Run the ETL docs pages about how the behavior of settings files has changed. With the dagster conversion, all the data sources are processed. Use dagit to processes individual datasources.
> Add new settings file behavior in docs

- .github/workflows/zenodo-cache-sync.yml
The `zenodo-cache-sync` [started to fail](https://github.com/catalyst-cooperative/pudl/actions/runs/4529236745/jobs/7976769364) because `pudl.workspace.setup.get_defaults()` couldn't find `PUDL_INPUT`, `PUDL_OUTPUT` or a `.pudl.yaml`. I fixed this by adding `PUDL_INPUT` and `PUDL_OUTPUT` env vars to the `zenodo-cache-sync` workflow.
I kicked off [a manual run](https://github.com/catalyst-cooperative/pudl/actions/runs/4578163390) of the action, and it passed.
> Add `PUDL_INPUT` and `PUDL_OUTPUT` vars to `zenodo-cache-sync` action

- src/pudl/metadata/resources/eia860.py
- src/pudl/output/denorm_eia.py
- src/pudl/output/pudltabl.py
> Dagsterize eia tables

- pyproject.toml
Add some additional project URLs that link to our release notes and donations page, so they are displayed on PyPI when we release a new version.
> Add funding and release notes URLs to the project.

- .github/workflows/com-dev-notify.yml
At some point, my workflow that notifies the `#community-dev` slack channel when a non-catalyst person creates a discussion or issue disappeared from main ##2211.  This PR adds it back!
I couldn't find anything in the main commit history :/
> Revive comdev notify action

- .github/workflows/run-etl.yml
Placeholder for the new build & deploy action that will be using google batch service instead of VMs.
> Boostrap for the run-etl action

- docs/release_notes.rst
- src/pudl/metadata/fields.py
Forgot to push these commits when I merged #2587
> Boiler cooler stack flue table (bb fixes)

- src/pudl/metadata/templates/datasette-metadata.yml.jinja
A majority of our technical support questions are still coming through pudl@catalyst.coop. We'd rather have people ask questions on GitHub discussions to make the answers public and searchable. The ["Contact Us"](https://github.com/catalyst-cooperative/pudl#contact-us) encourages users to ask support questions on Github discussions and send private communications to pudl@catalyst.coop. This makes me think users are sending emails to pudl@catalyst.coop because it is the primary contact method on data.catalyst.coop:
To funnel people towards github discussions instead of pudl@catalyst.coop, I've replaced the pudl@catalyst.coop link on datasette with a link to a new "Help Me!" github discussion.
> Replace pudl@catalyst.coop with github discussion link on datasette

- src/pudl/extract/dbf.py
Earlier, generic `KeyError` was thrown here. This resulted in the code silently bypassing archives that did not have correct dbc path as the `KeyError` was also caught when tables were missing.
Perhaps there could be further schema tests along the lines of - each year/archive should have at least 90% of the known tables present. This could catch situation where we are, for whatever reason, not reading the tables from some partitions.
> Throw different exception when dbc file is missing

- .pre-commit-config.yaml
- pyproject.toml
- src/pudl/analysis/allocate_net_gen.py
- src/pudl/analysis/mcoe.py
- src/pudl/analysis/plant_parts_eia.py
- src/pudl/extract/dbf.py
- src/pudl/extract/epacems.py
- src/pudl/metadata/enums.py
- src/pudl/metadata/templates/datasette-metadata.yml.jinja
- src/pudl/validate.py
- tox.ini
- Re-throw KeyError as specific exception when dbc file missing.
- Replace pudl@catalyst.coop with github discussion link on datasette
- [pre-commit.ci] pre-commit autoupdate
- [pre-commit.ci] auto fixes from pre-commit.com hooks
- remove flaky docformatter
- Undo docformatter mistakes that broke URLs.
> Merge dev into main for 2023-06-15

- pyproject.toml
> Upgrade to ferc-xbrl-extractor v0.8.3

- test/validate/ferc1_test.py
Update the expected number of rows in the `plant_in_service_ferc` table, after reducing the number of spot fixes.
> Update plant_in_service_ferc1 expected row count

- src/pudl/transform/ferc1.py
I added an aggregated factoid into the `utility_plant_summary_ferc1` table for two factoids that *when combined* link up to a record in the `plant_in_service_ferc1` table.
RN I added a calculation that is testing this linkage within the table. But what we what is to point this new factoid at the line in the pis table as a new pass through calc.
We can *either* do that by:
*  just having one calculation that links the electric portion of this record up to the PIS table - effectively stranding the non-electric break out of `utility_plant_in_service_classified` and `utility_plant_in_service_property_under_capital_leases`. So we'd get gas/other/etc "leaves" (most detailed factoids) as this new aggregated record and the electric leaves would keep going up along the chain into the pis table.
* …
> `utility_plant_summary_ferc1` to `plant_in_service_ferc1` link

- devtools/datasette/publish.sh
Forgot to add FERC 60 to the Datasette deployment.
> Add old FERC 60 DBF data to the Datasette deployment.

- docs/data_access.rst
Adds FERC60 to the data access documentation after it was added in #2734.
> Add FERC60 to data access docs

- src/pudl/transform/ferc1.py
Keep the calculation component records that only have parents and no children -- these represent reported values (leaves) in the tree.
> Don't drop leaf calculation components from calc comps table.

- src/pudl/workspace/setup_cli.py
A couple of lingering renames from #2640 that broke the docker build. 
The docker image was [able to build](https://github.com/catalyst-cooperative/pudl/actions/runs/5894257295).
> Fix `pudl_setup` `pudl_in` and `pudl_out` args

- .github/workflows/zenodo-cache-sync.yml
- .gitignore
- src/pudl/workspace/datastore.py
Add the production DOI for the PHMSA Natural Gas Annual Report archives on Zenodo to the datastore script so we can download and sync it to GCS and start with the extraction work.
> Add PHMSA Natural Gas annual report DOI to datastore.

- devtools/datasette/publish.sh
The datasette deployment was manually upgraded to use 32 GB of memory but was not changed in the deployment script so it went back to using 4GB of memory. This resulted in our datasette deployment having stale data.
> Increase datasette cloud run memory from 4GB to 32GB

- .gitattributes
- environments/conda-linux-64.lock.yml
- environments/conda-lock.yml
- environments/conda-osx-64.lock.yml
- environments/conda-osx-arm64.lock.yml
In case of conflicts within our conda lockfiles, always use the version on the current branch ("ours") when merging.
> Always take lockfile version from current branch when merging

- .github/workflows/update-conda-lockfile.yml
- Makefile
- docs/conf.py
- docs/dev/dev_setup.rst
- environments/conda-linux-64.lock.yml
- environments/conda-lock.yml
- environments/conda-osx-64.lock.yml
- environments/conda-osx-arm64.lock.yml
- Merge dev into main for 2023-11-22 (#3077)
- Updates docs on ruff, git config, pudl-dev environment.
- Simplify process of bootstrapping pudl-dev conda env. (#3080)
> Merge dev into main for 2023-11-23

- .github/workflows/build-deploy-pudl.yml
1. use runtime timestamp instead of commit timestamp
2. try to fix the github ref calculation
3. add full output path to the slack notification
> Merge dev into main for 2023-12-15

- CONTRIBUTING.rst
- docs/data_sources/wip_future.rst
As discussed in our community development meeting, we'd like to provide clearer documentation about making knowledge contributions. Here's a stab at it.
> Knowledge contribution docs

- docs/data_access.rst
- docs/templates/data_source_parent.rst.jinja
- docs/templates/epacems_child.rst.jinja
- src/pudl/metadata/classes.py
- src/pudl/metadata/sources.py
- Remove references to defunct PUDL Catalog
- Remove link to defunct EPA FTP site.
- Update link to EPA CEMS nightly build outputs
- Remove duplicative and flaky source vs. working partitions in data source template. Just show temporal coverage.
- Update EPA CEMS row count
Ran the docs build locally and inspected the output.
```[tasklist]
```
> Update EPA CEMS docs for quarterly data, new table name.

- environments/conda-linux-64.lock.yml
- environments/conda-lock.yml
- environments/conda-osx-64.lock.yml
- environments/conda-osx-arm64.lock.yml
> Update conda lockfile for week of 2024-01-08

- devtools/datasette/publish.py
Closes #XXXX.
```[tasklist]
```
> Generalize passing args through to flyctl deploy

- docs/release_notes.rst
- src/pudl/output/ferc1.py
- src/pudl/transform/ferc1.py
- src/pudl/transform/params/ferc1.py
Closes #3233.
* simple replace of contents of annual column with quarterly column's content
```[tasklist]
```
> fill in the annual columns with quarterly balances

- .github/ISSUE_TEMPLATE/nightly_build_failure.md
Closes #3284 .
There was no action needed to resolve #3284, except for verifying that these things did indeed happen. I'm adding an issue template so we can handle these more smoothly in the future!
I'm not actually sure how to test if issue templates are properly formatted, but we can verify this once merged by trying to create an issue!
```[tasklist]
```
> Add issue template for nightly build

- devtools/zenodo/zenodo_data_release.py
Closes #3298 .
Zenodo sandbox has been a bit flaky, this adds retries to handle the flakiness & also lets us simply kick off manual retries by syncing directly from a cloud bucket.
Ran the dang thing with both `gs://pudl.catalyst.coop/nightly` as well as a local directory, and saw that the Zenodo draft release had the correct files in it each time.
In terms of automated testing, as of now we basically test it every time we run a nightly build. If we want to test it in CI or something, I think we'd have to set up:
- a small GCS bucket with some stuff in it
- a sandbox Zenodo record to run tests in
And then we would have to try syncing from GCS to that record, verifying that the record has what we expect, and then doing the …
> Add retries, and use fsspec to handle GCS

- environments/conda-linux-64.lock.yml
- environments/conda-lock.yml
- environments/conda-osx-64.lock.yml
- environments/conda-osx-arm64.lock.yml
> Update conda lockfile for week of 2024-01-29

- docs/release_notes.rst
Close out release notes in anticipation of PUDL v2024.02.03
I ran the docs build locally and it looked good.
```[tasklist]
```
> Update release notes for PUDL v2024.02.03

- src/pudl/workspace/datastore.py
Update the EIA Bulk Electricity archive to the most recent DOI.
Closes #3348
- I ran the full ETL locally and it went fine.
- Ran the data validations locally and they all passed!
```[tasklist]
```
> Update EIA Bulk Electricity archive DOI

- environments/conda-linux-64.lock.yml
- environments/conda-lock.yml
- environments/conda-osx-64.lock.yml
- environments/conda-osx-arm64.lock.yml
> Update conda lockfile for week of 2024-03-04

- src/pudl/extract/excel.py
Came up in #3453, though not the root cause of the failure.
We now zip 860M files, making it unnecessary to handle both Excel and Zipfile formats in our Excel reader by default. As noted in https://github.com/catalyst-cooperative/pudl/issues/3453#issuecomment-1985994259, we can subclass the `load_source` method as needed for a particular archiver if it is formatted differently than our standard zipped files. This should avoid unnecessary read-in calls that are expected to fail.
Dropped some crufty code in `pudl.extract.excel`.
Materialize some raw Excel assets, or run `make pytest-coverage`.
```[tasklist]
```
> Delete unused try/except Excel read-in method in `pudl.extract.excel`

- .pre-commit-config.yaml
- environments/conda-linux-64.lock.yml
- environments/conda-lock.yml
- environments/conda-osx-64.lock.yml
- environments/conda-osx-arm64.lock.yml
> Update conda lockfile for week of 2024-03-18

- environments/conda-linux-64.lock.yml
- environments/conda-lock.yml
- environments/conda-osx-64.lock.yml
- environments/conda-osx-arm64.lock.yml
> Update conda lockfile for week of 2024-03-25

- src/pudl/package_data/settings/etl_full.yml
Closes #3520 
Fixes indentation error in full ETL settings.
Run EIA 861 raw extraction from within full ETL config in Dagster.
```[tasklist]
```
> Fix indent error in nightly builds

- environments/conda-linux-64.lock.yml
- environments/conda-lock.yml
- environments/conda-osx-64.lock.yml
- environments/conda-osx-arm64.lock.yml
> Update conda lockfile for week of 2024-04-01

- src/pudl/extract/eia860m.py
- src/pudl/settings.py
- test/unit/settings_test.py
The comments and suggestions on #3625 were getting a bit hard to disentangle, so here is a little PR that can be compared more legibly maybe.
This fixes the failing unit test and some other minor issues, but I think there are still issues to be resolved in the validation logic and additional tests which should be added to make sure this somewhat complicated setting is really doing what we want it to be doing.
> Tweak eia860m settings validations and tests.

- environments/conda-linux-64.lock.yml
- environments/conda-lock.yml
- environments/conda-osx-64.lock.yml
- environments/conda-osx-arm64.lock.yml
> Update conda lockfile for week of 2024-05-20

- .pre-commit-config.yaml
- devtools/zenodo/zenodo_data_release.py
- environments/conda-linux-64.lock.yml
- environments/conda-lock.yml
- environments/conda-osx-64.lock.yml
- environments/conda-osx-arm64.lock.yml
> Update conda lockfile for week of 2024-06-03

- .pre-commit-config.yaml
- environments/conda-linux-64.lock.yml
- environments/conda-lock.yml
- environments/conda-osx-64.lock.yml
- environments/conda-osx-arm64.lock.yml
> Update conda lockfile for week of 2024-06-10

- environments/conda-linux-64.lock.yml
- environments/conda-lock.yml
- environments/conda-osx-64.lock.yml
- environments/conda-osx-arm64.lock.yml
> Update conda lockfile for week of 2024-06-17

- .pre-commit-config.yaml
- devtools/datasette/publish.py
- environments/conda-linux-64.lock.yml
- environments/conda-lock.yml
- environments/conda-osx-64.lock.yml
- environments/conda-osx-arm64.lock.yml
- src/pudl/convert/censusdp1tract_to_sqlite.py
> Update conda lockfile for week of 2024-07-01

- .pre-commit-config.yaml
- environments/conda-linux-64.lock.yml
- environments/conda-lock.yml
- environments/conda-osx-64.lock.yml
- environments/conda-osx-arm64.lock.yml
> Update conda lockfile for week of 2024-07-08

- test/validate/mcoe_test.py
Closes #3733.
**What problem does this address?**
Fix nightly build fail.
**What did you change?**
updates minmax row validation tests in the `mcoe` module.
> Eia923 er validation test fix

- .pre-commit-config.yaml
- environments/conda-linux-64.lock.yml
- environments/conda-lock.yml
- environments/conda-osx-64.lock.yml
- environments/conda-osx-arm64.lock.yml
> Update conda lockfile for week of 2024-08-05

- .pre-commit-config.yaml
- devtools/zenodo/zenodo_data_release.py
- environments/conda-linux-64.lock.yml
- environments/conda-lock.yml
- environments/conda-osx-64.lock.yml
- environments/conda-osx-arm64.lock.yml
> Update conda lockfile for week of 2024-08-26

- README.rst
- docs/index.rst
**What problem does this address?**
The fact that people don't know how to pronounce PUDL
**What did you change?**
Added "(pronounced puddle)" to the docs and the README.
**How did you make sure this worked? How can a reviewer verify this?**
Successfully ran `make docs-build`
> Add PUDL pronunciation to docs and README

- .github/workflows/update-conda-lockfile.yml
- environments/conda-linux-64.lock.yml
- environments/conda-lock.yml
- environments/conda-osx-64.lock.yml
- environments/conda-osx-arm64.lock.yml
> Update conda lockfile for week of 2024-09-09

- .pre-commit-config.yaml
- environments/conda-linux-64.lock.yml
- environments/conda-lock.yml
- environments/conda-osx-64.lock.yml
- environments/conda-osx-arm64.lock.yml
> Update conda lockfile for week of 2024-09-16

- .pre-commit-config.yaml
- environments/conda-linux-64.lock.yml
- environments/conda-lock.yml
- environments/conda-osx-64.lock.yml
- environments/conda-osx-arm64.lock.yml
> Update conda lockfile for week of 2024-09-23

- src/pudl/metadata/sources.py
percentage vs. fraction because the raw data is on a scale of 0-100 vs. 0-1
> Update language in vcerare datasource description

- .zenodo.json
- CITATION.cff
- docs/release_notes.rst
> Close out release notes and repo metadata for v2024.10.0

- .pre-commit-config.yaml
- environments/conda-linux-64.lock.yml
- environments/conda-lock.yml
- environments/conda-osx-64.lock.yml
- environments/conda-osx-arm64.lock.yml
> Update conda lockfile for week of 2024-11-04

- docs/release_notes.rst
- src/pudl/workspace/datastore.py
Closes #3942.
Updating EIA 930 data as part of the quarterly release process.
- Update the DOI on EIA 930 data.
- Update the release notes.
```[tasklist]
```
```[tasklist]
```
> Integrate EIA 930 data up through October

- .pre-commit-config.yaml
- environments/conda-linux-64.lock.yml
- environments/conda-lock.yml
- environments/conda-osx-64.lock.yml
- environments/conda-osx-arm64.lock.yml
> Update conda lockfile for week of 2024-11-11

- .pre-commit-config.yaml
- environments/conda-linux-64.lock.yml
- environments/conda-lock.yml
- environments/conda-osx-64.lock.yml
- environments/conda-osx-arm64.lock.yml
- test/integration/zenodo_datapackage_test.py
> Update conda lockfile for week of 2024-11-25

- environments/conda-linux-64.lock.yml
- environments/conda-lock.yml
- environments/conda-osx-64.lock.yml
- environments/conda-osx-arm64.lock.yml
> Update conda lockfile for week of 2024-12-09

- environments/conda-linux-64.lock.yml
- environments/conda-lock.yml
- environments/conda-osx-64.lock.yml
- environments/conda-osx-arm64.lock.yml
> Update conda lockfile for week of 2024-12-16

- environments/conda-linux-64.lock.yml
- environments/conda-lock.yml
- environments/conda-osx-64.lock.yml
- environments/conda-osx-arm64.lock.yml
> Update conda lockfile for week of 2024-12-30

- environments/conda-linux-64.lock.yml
- environments/conda-lock.yml
- environments/conda-osx-64.lock.yml
- environments/conda-osx-arm64.lock.yml
> Update conda lockfile for week of 2025-01-06

- environments/conda-linux-64.lock.yml
- environments/conda-lock.yml
- environments/conda-osx-64.lock.yml
- environments/conda-osx-arm64.lock.yml
> Update conda lockfile for week of 2025-01-20

- .pre-commit-config.yaml
- environments/conda-linux-64.lock.yml
- environments/conda-lock.yml
- environments/conda-osx-64.lock.yml
- environments/conda-osx-arm64.lock.yml
> Update conda lockfile for week of 2025-01-27

- docs/catalyst_cites.bib
- docs/catalyst_pubs.bib
Our bibliography and citations file are out of date!
Updated them! And reordered `catalyst_cites.bib` into more or less chronological order (reordered by year, if not by month).
```[tasklist]
```
> Update PUDL bibliography

- docs/release_notes.rst
- src/pudl/metadata/sources.py
- src/pudl/workspace/datastore.py
Closes #4041 .
adds new doi
update source partition
```[tasklist]
```
I ran the daster assets down and upstream or the hourly emissions table (via `*"core_epacems__hourly_emissions"*`)/ These assets all generated just fine.
I checked for unit, integration and validation tests. There are unit tests which are passing and not really directly accessing 2024.
I did check the annual row counts and found this (which looks good):
```python
{
1995: 3846120,
1996: 3645432,
1997: 17660784,
1998: 18073848,
1999: 22004256,
2000: 23553696,
2001: 26200776,
2002: 30017256,
2003: 33568728,
2004: 35335080,
2005: 35838552,
2006: 36210960,
2007: 36405240,
2008: 40525032,
2009: 40320840,
2010: 40499832,
2011: 40665552,
2012: 40614648,
2013: 40114824, …
```
> Add Q4 2024 CEMS data to ETL

- devtools/datasette/fly/production.toml
We've been seeing lots of 502s from our healthcheck.
Starting 2025-02-08 we've been receiving a lot more traffic - big spikes that last for 1-1.5h, starting every 4.5h. During those spikes, we've run into a lot of `Concurrency limit of 25 connections reached` messages. Looking at our metrics, we seem to be pretty consistently running at a load average of about 14-15% during those spikes, so I think we can safely raise our max concurrent connections from 25 to 80.
Changed the production concurrency limit in the app config.
```[tasklist]
```
Currently downloading nightly build outputs from S3 and did a test deploy.
```[tasklist]
```
> fix: up fly.io app concurrency limit to avoid 502s

- docs/catalyst_cites.bib
Found these while building a draft of the next newsletter!
Includes the PhD thesis of one of the authors of the racial disparities paper we mentioned in the last newsletter. go CMU EPP! 🖤 💛
> New citations!

- src/pudl/metadata/templates/datasette-metadata.yml.jinja
Part of catalyst-cooperative/parquet-fe-prototype#21
We need to warn people that datasette will be going down... eventually.
Added a 'mid-2025' deprecation warning for datasette.
```[tasklist]
```
Ran `python publish.py --only ferc6_xbrl.sqlite --local` to make sure the copy didn't break.
```[tasklist]
```
> chore: add deprecation warning to datasette template

- docker/Dockerfile
- environments/conda-linux-64.lock.yml
- environments/conda-lock.yml
- environments/conda-osx-64.lock.yml
- environments/conda-osx-arm64.lock.yml
> Update conda lockfile for week of 2025-03-17

- environments/conda-linux-64.lock.yml
- environments/conda-lock.yml
- environments/conda-osx-64.lock.yml
- environments/conda-osx-arm64.lock.yml
> Update conda lockfile for week of 2025-03-31

- src/pudl/metadata/sources.py
- src/pudl/settings.py
Update SEC10k `sources` metadata to be consistent with archiver, and add `Sec10kSettings` class.
> Make sec10k metadata consistent with archiver

- .pre-commit-config.yaml
- environments/conda-linux-64.lock.yml
- environments/conda-lock.yml
- environments/conda-osx-64.lock.yml
- environments/conda-osx-arm64.lock.yml
> Update conda lockfile for week of 2025-04-28

- .pre-commit-config.yaml
- docker/Dockerfile
- environments/conda-linux-64.lock.yml
- environments/conda-lock.yml
- environments/conda-osx-64.lock.yml
- environments/conda-osx-arm64.lock.yml
> Update conda lockfile for week of 2025-05-05

- .github/workflows/update-conda-lockfile.yml
- environments/conda-linux-64.lock.yml
- environments/conda-lock.yml
- environments/conda-osx-64.lock.yml
- environments/conda-osx-arm64.lock.yml
> Update conda lockfile for week of 2025-05-11

- .zenodo.json
- CITATION.cff
- docs/release_notes.rst
- Update release notes
- Update `.zenodo.json` creator metadata
- Update `CITATION.cff` citation metadata
Part of #4278
> Close out release notes for v2025.5.0

- .pre-commit-config.yaml
- environments/conda-linux-64.lock.yml
- environments/conda-lock.yml
- environments/conda-osx-64.lock.yml
- environments/conda-osx-arm64.lock.yml
> Update conda lockfile for week of 2025-06-01

- .pre-commit-config.yaml
- environments/conda-linux-64.lock.yml
- environments/conda-lock.yml
- environments/conda-osx-64.lock.yml
- environments/conda-osx-arm64.lock.yml
Update to get a significant update to `geopandas` so I can see if it creates issues...
> Update conda lockfile

- .github/workflows/update-conda-lockfile.yml
- .pre-commit-config.yaml
- dbt/package-lock.yml
- environments/conda-linux-64.lock.yml
- environments/conda-lock.yml
- environments/conda-osx-64.lock.yml
- environments/conda-osx-arm64.lock.yml
> Update conda lockfile for week of 2025-06-29

- .zenodo.json
- CITATION.cff
- docs/release_notes.rst
> Close out release notes for PUDL v2025.7.0

- .pre-commit-config.yaml
- environments/conda-linux-64.lock.yml
- environments/conda-lock.yml
- environments/conda-osx-64.lock.yml
- environments/conda-osx-arm64.lock.yml
- src/pudl/etl/__init__.py
> Update conda lockfile for week of 2025-07-20
